<!DOCTYPE html>
<html xmlns="http://www.w3.org/1999/xhtml" lang="en" xml:lang="en"><head>

<meta charset="utf-8">
<meta name="generator" content="quarto-1.3.353">

<meta name="viewport" content="width=device-width, initial-scale=1.0, user-scalable=yes">


<title>Khoa học dữ liệu với R - 25&nbsp; Xây dựng mô hình với H2O</title>
<style>
code{white-space: pre-wrap;}
span.smallcaps{font-variant: small-caps;}
div.columns{display: flex; gap: min(4vw, 1.5em);}
div.column{flex: auto; overflow-x: auto;}
div.hanging-indent{margin-left: 1.5em; text-indent: -1.5em;}
ul.task-list{list-style: none;}
ul.task-list li input[type="checkbox"] {
  width: 0.8em;
  margin: 0 0.8em 0.2em -1em; /* quarto-specific, see https://github.com/quarto-dev/quarto-cli/issues/4556 */ 
  vertical-align: middle;
}
/* CSS for syntax highlighting */
pre > code.sourceCode { white-space: pre; position: relative; }
pre > code.sourceCode > span { display: inline-block; line-height: 1.25; }
pre > code.sourceCode > span:empty { height: 1.2em; }
.sourceCode { overflow: visible; }
code.sourceCode > span { color: inherit; text-decoration: inherit; }
div.sourceCode { margin: 1em 0; }
pre.sourceCode { margin: 0; }
@media screen {
div.sourceCode { overflow: auto; }
}
@media print {
pre > code.sourceCode { white-space: pre-wrap; }
pre > code.sourceCode > span { text-indent: -5em; padding-left: 5em; }
}
pre.numberSource code
  { counter-reset: source-line 0; }
pre.numberSource code > span
  { position: relative; left: -4em; counter-increment: source-line; }
pre.numberSource code > span > a:first-child::before
  { content: counter(source-line);
    position: relative; left: -1em; text-align: right; vertical-align: baseline;
    border: none; display: inline-block;
    -webkit-touch-callout: none; -webkit-user-select: none;
    -khtml-user-select: none; -moz-user-select: none;
    -ms-user-select: none; user-select: none;
    padding: 0 4px; width: 4em;
  }
pre.numberSource { margin-left: 3em;  padding-left: 4px; }
div.sourceCode
  {   }
@media screen {
pre > code.sourceCode > span > a:first-child::before { text-decoration: underline; }
}
</style>


<script src="site_libs/quarto-nav/quarto-nav.js"></script>
<script src="site_libs/quarto-nav/headroom.min.js"></script>
<script src="site_libs/clipboard/clipboard.min.js"></script>
<script src="site_libs/quarto-search/autocomplete.umd.js"></script>
<script src="site_libs/quarto-search/fuse.min.js"></script>
<script src="site_libs/quarto-search/quarto-search.js"></script>
<meta name="quarto:offset" content="./">
<link href="./p03-08-xgboost.html" rel="next">
<link href="./p03-05-bagging-boosting.html" rel="prev">
<script src="site_libs/quarto-html/quarto.js"></script>
<script src="site_libs/quarto-html/popper.min.js"></script>
<script src="site_libs/quarto-html/tippy.umd.min.js"></script>
<script src="site_libs/quarto-html/anchor.min.js"></script>
<link href="site_libs/quarto-html/tippy.css" rel="stylesheet">
<link href="site_libs/quarto-html/quarto-syntax-highlighting.css" rel="stylesheet" class="quarto-color-scheme" id="quarto-text-highlighting-styles">
<link href="site_libs/quarto-html/quarto-syntax-highlighting-dark.css" rel="prefetch" class="quarto-color-scheme quarto-color-alternate" id="quarto-text-highlighting-styles">
<script src="site_libs/bootstrap/bootstrap.min.js"></script>
<link href="site_libs/bootstrap/bootstrap-icons.css" rel="stylesheet">
<link href="site_libs/bootstrap/bootstrap.min.css" rel="stylesheet" class="quarto-color-scheme" id="quarto-bootstrap" data-mode="light">
<link href="site_libs/bootstrap/bootstrap-dark.min.css" rel="prefetch" class="quarto-color-scheme quarto-color-alternate" id="quarto-bootstrap" data-mode="dark">
<link href="site_libs/quarto-contrib/bookup_fonts_embed-0.0/fonts-download.css" rel="stylesheet">
<script id="quarto-search-options" type="application/json">{
  "location": "sidebar",
  "copy-button": false,
  "collapse-after": 3,
  "panel-placement": "start",
  "type": "textbox",
  "limit": 20,
  "language": {
    "search-no-results-text": "No results",
    "search-matching-documents-text": "matching documents",
    "search-copy-link-title": "Copy link to search",
    "search-hide-matches-text": "Hide additional matches",
    "search-more-match-text": "more match in this document",
    "search-more-matches-text": "more matches in this document",
    "search-clear-button-title": "Clear",
    "search-detached-cancel-button-title": "Cancel",
    "search-submit-button-title": "Submit"
  }
}</script>


</head>

<body class="nav-sidebar docked">


<div id="quarto-search-results"></div>
  <header id="quarto-header" class="headroom fixed-top">
  <nav class="quarto-secondary-nav">
    <div class="container-fluid d-flex">
      <button type="button" class="quarto-btn-toggle btn" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar,#quarto-sidebar-glass" aria-controls="quarto-sidebar" aria-expanded="false" aria-label="Toggle sidebar navigation" onclick="if (window.quartoToggleHeadroom) { window.quartoToggleHeadroom(); }">
        <i class="bi bi-layout-text-sidebar-reverse"></i>
      </button>
      <nav class="quarto-page-breadcrumbs" aria-label="breadcrumb"><ol class="breadcrumb"><li class="breadcrumb-item"><a href="./p03-01-gioi-thieu-hoc-may.html">Supervised Learning</a></li><li class="breadcrumb-item"><a href="./p03-07-xay-dung-mo-hinh-voi-h2o.html"><span class="chapter-number">25</span>&nbsp; <span class="chapter-title">Xây dựng mô hình với H2O</span></a></li></ol></nav>
      <a class="flex-grow-1" role="button" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar,#quarto-sidebar-glass" aria-controls="quarto-sidebar" aria-expanded="false" aria-label="Toggle sidebar navigation" onclick="if (window.quartoToggleHeadroom) { window.quartoToggleHeadroom(); }">      
      </a>
      <button type="button" class="btn quarto-search-button" aria-label="Search" onclick="window.quartoOpenSearch();">
        <i class="bi bi-search"></i>
      </button>
    </div>
  </nav>
</header>
<!-- content -->
<div id="quarto-content" class="quarto-container page-columns page-rows-contents page-layout-article">
<!-- sidebar -->
  <nav id="quarto-sidebar" class="sidebar collapse collapse-horizontal sidebar-navigation docked overflow-auto">
    <div class="pt-lg-2 mt-2 text-left sidebar-header">
    <div class="sidebar-title mb-0 py-0">
      <a href="./">Khoa học dữ liệu với R</a> 
        <div class="sidebar-tools-main">
  <a href="" class="quarto-color-scheme-toggle quarto-navigation-tool  px-1" onclick="window.quartoToggleColorScheme(); return false;" title="Toggle dark mode"><i class="bi"></i></a>
  <a href="" class="quarto-reader-toggle quarto-navigation-tool px-1" onclick="window.quartoToggleReader(); return false;" title="Toggle reader mode">
  <div class="quarto-reader-toggle-btn">
  <i class="bi"></i>
  </div>
</a>
</div>
    </div>
      </div>
        <div class="mt-2 flex-shrink-0 align-items-center">
        <div class="sidebar-search">
        <div id="quarto-search" class="" title="Search"></div>
        </div>
        </div>
    <div class="sidebar-menu-container"> 
    <ul class="list-unstyled mt-1">
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./index.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">1</span>&nbsp; <span class="chapter-title">Khoa học dữ liệu và nghề phân tích dữ liệu</span></span></a>
  </div>
</li>
        <li class="sidebar-item sidebar-item-section">
      <div class="sidebar-item-container"> 
            <a class="sidebar-item-text sidebar-link text-start" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-1" aria-expanded="true">
 <span class="menu-text">Phân tích khám phá dữ liệu</span></a>
          <a class="sidebar-item-toggle text-start" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-1" aria-expanded="true" aria-label="Toggle section">
            <i class="bi bi-chevron-right ms-2"></i>
          </a> 
      </div>
      <ul id="quarto-sidebar-section-1" class="collapse list-unstyled sidebar-section depth1 show">  
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./p02-01-gioi-thieu-co-ban-ve-r.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">2</span>&nbsp; <span class="chapter-title">Giới thiệu cơ bản về R</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./p02-03-xay-dung-bao-cao-voi-rmarkdown-quarto.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">3</span>&nbsp; <span class="chapter-title">Xây dựng báo cáo với Rmarkdown &amp; Quarto</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./p02-03-import-du-lieu.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">4</span>&nbsp; <span class="chapter-title">Import dữ liệu</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./p02-02-bien-doi-du-lieu-dplyr.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">5</span>&nbsp; <span class="chapter-title">Ngữ pháp của biến đổi dữ liệu với DPLYR</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./p02-03-phan-ra-va-xoay-chieu-du-lieu.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">6</span>&nbsp; <span class="chapter-title">Làm sạch và biến đổi dữ liệu nâng cao</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./p02-04-ngu-phap-bieu-do-ggplot2.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">7</span>&nbsp; <span class="chapter-title">Ngữ pháp của biểu đồ với <code>ggplot2</code></span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./p02-05-cac-chi-so-thong-ke.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">8</span>&nbsp; <span class="chapter-title">Các chỉ số thống kê mô tả cơ bản</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./p02-06-lap-trinh-ham.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">9</span>&nbsp; <span class="chapter-title">Lập trình hàm</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./p02-07-lap-trinh-ham-voi-purrr.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">10</span>&nbsp; <span class="chapter-title">Lập trình chức năng hàm với purrr</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./p02-08-bien-doi-du-lieu-text.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">11</span>&nbsp; <span class="chapter-title">Biến đổi dữ liệu text</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./p02-09-bien-doi-du-lieu-thoi-gian.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">12</span>&nbsp; <span class="chapter-title">Biến đổi dữ liệu thời gian</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./p02-11-quan-ly-nhieu-mo-hinh.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">13</span>&nbsp; <span class="chapter-title">Quản lý kết quả phân tích từ nhiều mô hình</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./p02-16-power-analysis.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">14</span>&nbsp; <span class="chapter-title">Power analysis</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./p02-20-sampling-methods.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">15</span>&nbsp; <span class="chapter-title">Phương pháp ước lượng tham số thông qua lấy mẫu</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./p02-50-datatable.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">16</span>&nbsp; <span class="chapter-title">Biến đổi dữ liệu với <code>data.table</code></span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./p02-51-du-lieu-lon.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">17</span>&nbsp; <span class="chapter-title">Cách thức xử lý dữ liệu lớn</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./p02-60-thu-thap-du-lieu-tu-website.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">18</span>&nbsp; <span class="chapter-title">Thu thập dữ liệu từ website</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./p02-99-meo-trong-r.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">19</span>&nbsp; <span class="chapter-title">Các mẹo trong R</span></span></a>
  </div>
</li>
      </ul>
  </li>
        <li class="sidebar-item sidebar-item-section">
      <div class="sidebar-item-container"> 
            <a class="sidebar-item-text sidebar-link text-start" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-2" aria-expanded="true">
 <span class="menu-text">Supervised Learning</span></a>
          <a class="sidebar-item-toggle text-start" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-2" aria-expanded="true" aria-label="Toggle section">
            <i class="bi bi-chevron-right ms-2"></i>
          </a> 
      </div>
      <ul id="quarto-sidebar-section-2" class="collapse list-unstyled sidebar-section depth1 show">  
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./p03-01-gioi-thieu-hoc-may.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">20</span>&nbsp; <span class="chapter-title">Giới thiệu về học máy</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./p03-02-mo-hinh-ols.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">21</span>&nbsp; <span class="chapter-title">Mô hình hồi quy tuyến tính</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./p03-03-logistic-regression.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">22</span>&nbsp; <span class="chapter-title">Mô hình hồi quy logistic</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./p03-04-decision-tree.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">23</span>&nbsp; <span class="chapter-title">Cây quyết định</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./p03-05-bagging-boosting.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">24</span>&nbsp; <span class="chapter-title">Bagging, RandomForest và Boosting</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./p03-07-xay-dung-mo-hinh-voi-h2o.html" class="sidebar-item-text sidebar-link active">
 <span class="menu-text"><span class="chapter-number">25</span>&nbsp; <span class="chapter-title">Xây dựng mô hình với H2O</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./p03-08-xgboost.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">26</span>&nbsp; <span class="chapter-title">XGBoost &amp; LightGBM</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./p03-10-knn.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">27</span>&nbsp; <span class="chapter-title">K nearest neighbors</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./p03-11-svm.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">28</span>&nbsp; <span class="chapter-title">Support Vector Machine</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./p03-15-nonlinear.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">29</span>&nbsp; <span class="chapter-title">Mô hình phi tuyến tính</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./p03-17-regularization.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">30</span>&nbsp; <span class="chapter-title">Lựa chọn biến &amp; regularization</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./p03-20-feature-engineering.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">31</span>&nbsp; <span class="chapter-title">Feature Engineering</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./p03-70-tidymodels.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">32</span>&nbsp; <span class="chapter-title">Tidymodels</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./p03-40-interpretable-ml.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">33</span>&nbsp; <span class="chapter-title">Giải thích mô hình học máy</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./p03-30-credit-scoring.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">34</span>&nbsp; <span class="chapter-title">Credit Scoring</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./p03-50-chat-luong-mo-hinh.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">35</span>&nbsp; <span class="chapter-title">Chất lượng mô hình</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./p03-75-mlops-vetiver.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">36</span>&nbsp; <span class="chapter-title">Deployment &amp; MLOPS</span></span></a>
  </div>
</li>
      </ul>
  </li>
        <li class="sidebar-item sidebar-item-section">
      <div class="sidebar-item-container"> 
            <a class="sidebar-item-text sidebar-link text-start" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-3" aria-expanded="true">
 <span class="menu-text">Unsupervised Learning</span></a>
          <a class="sidebar-item-toggle text-start" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-3" aria-expanded="true" aria-label="Toggle section">
            <i class="bi bi-chevron-right ms-2"></i>
          </a> 
      </div>
      <ul id="quarto-sidebar-section-3" class="collapse list-unstyled sidebar-section depth1 show">  
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./p04-01-unsupervised-learning.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">37</span>&nbsp; <span class="chapter-title">Unsupervised learning</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./p04-02-hierarchical-clustering.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">38</span>&nbsp; <span class="chapter-title">Hierachical clustering</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./p04-03-kmeans.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">39</span>&nbsp; <span class="chapter-title">k-means</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./p04-04-basket-analysis.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">40</span>&nbsp; <span class="chapter-title">Phân tích giỏ hàng</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./p04-05-pca.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">41</span>&nbsp; <span class="chapter-title">Principal component analysis</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./p04-06-factor-analysis.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">42</span>&nbsp; <span class="chapter-title">Phân tích nhân tố ẩn (factor analysis)</span></span></a>
  </div>
</li>
      </ul>
  </li>
        <li class="sidebar-item sidebar-item-section">
      <div class="sidebar-item-container"> 
            <a class="sidebar-item-text sidebar-link text-start" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-4" aria-expanded="true">
 <span class="menu-text">Chuỗi thời gian</span></a>
          <a class="sidebar-item-toggle text-start" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-4" aria-expanded="true" aria-label="Toggle section">
            <i class="bi bi-chevron-right ms-2"></i>
          </a> 
      </div>
      <ul id="quarto-sidebar-section-4" class="collapse list-unstyled sidebar-section depth1 show">  
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./p05-01-chuoi-thoi-gian.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">43</span>&nbsp; <span class="chapter-title">Giới thiệu về chuỗi thời gian</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./p05-02-arima.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">44</span>&nbsp; <span class="chapter-title">Mô hình ARIMA</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./p05-07-du-bao-ts-voi-timetk.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">45</span>&nbsp; <span class="chapter-title">Dự báo chuỗi thời gian với học máy</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./p05-08-abnomaly-detection.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">46</span>&nbsp; <span class="chapter-title">Abnomaly detection trong times series</span></span></a>
  </div>
</li>
      </ul>
  </li>
        <li class="sidebar-item sidebar-item-section">
      <div class="sidebar-item-container"> 
            <a class="sidebar-item-text sidebar-link text-start" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-5" aria-expanded="true">
 <span class="menu-text">Xử lý ngôn ngữ tự nhiên</span></a>
          <a class="sidebar-item-toggle text-start" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-5" aria-expanded="true" aria-label="Toggle section">
            <i class="bi bi-chevron-right ms-2"></i>
          </a> 
      </div>
      <ul id="quarto-sidebar-section-5" class="collapse list-unstyled sidebar-section depth1 show">  
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./p06-01-nlp-co-ban.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">47</span>&nbsp; <span class="chapter-title">Xử lý ngôn ngữ tự nhiên</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./p06-04-text-classification.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">48</span>&nbsp; <span class="chapter-title">Phân loại text</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./p06-07-nlp-api.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">49</span>&nbsp; <span class="chapter-title">Sử dụng API từ các dịch vụ đám mây</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./p06-10-ocr-tesseract.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">50</span>&nbsp; <span class="chapter-title">OCR với <code>tesseract</code></span></span></a>
  </div>
</li>
      </ul>
  </li>
        <li class="sidebar-item sidebar-item-section">
      <div class="sidebar-item-container"> 
            <a class="sidebar-item-text sidebar-link text-start" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-6" aria-expanded="true">
 <span class="menu-text">Các phương pháp phân tích khác</span></a>
          <a class="sidebar-item-toggle text-start" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-6" aria-expanded="true" aria-label="Toggle section">
            <i class="bi bi-chevron-right ms-2"></i>
          </a> 
      </div>
      <ul id="quarto-sidebar-section-6" class="collapse list-unstyled sidebar-section depth1 show">  
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./p07-03-collaborative-filtering.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">51</span>&nbsp; <span class="chapter-title">Collaborative Filtering</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./p07-04-survival-analysis.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">52</span>&nbsp; <span class="chapter-title">Survival Analysis</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./p07-05-vintage-analysis.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">53</span>&nbsp; <span class="chapter-title">Vintage analysis</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./p07-06-rfm.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">54</span>&nbsp; <span class="chapter-title">Mô hình RFM</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./p07-07-spatial-data.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">55</span>&nbsp; <span class="chapter-title">Spatial data</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./p07-08-anomaly-detection.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">56</span>&nbsp; <span class="chapter-title">Abnomaly detection</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./p07-15-quantile-regression.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">57</span>&nbsp; <span class="chapter-title">Hồi quy phân vị</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./p07-16-retention-analysis.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">58</span>&nbsp; <span class="chapter-title">Retention analysis</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./p07-20-network-analysis.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">59</span>&nbsp; <span class="chapter-title">Network analysis</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./p07-21-dea.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">60</span>&nbsp; <span class="chapter-title">Data Envelopment Analysis</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./p07-22-bupar.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">61</span>&nbsp; <span class="chapter-title">Business Process Analytics</span></span></a>
  </div>
</li>
      </ul>
  </li>
        <li class="sidebar-item sidebar-item-section">
      <div class="sidebar-item-container"> 
            <a class="sidebar-item-text sidebar-link text-start" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-7" aria-expanded="true">
 <span class="menu-text">Cloud Computing</span></a>
          <a class="sidebar-item-toggle text-start" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-7" aria-expanded="true" aria-label="Toggle section">
            <i class="bi bi-chevron-right ms-2"></i>
          </a> 
      </div>
      <ul id="quarto-sidebar-section-7" class="collapse list-unstyled sidebar-section depth1 show">  
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./p10-01-cai-dat-rstudio-server-tren-amazon.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">62</span>&nbsp; <span class="chapter-title">Cài đặt server RStudio trên Amazon</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./p10-03-web-service-azure.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">63</span>&nbsp; <span class="chapter-title">Xây dựng web service với Azure</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./p10-09-apis-voi-plumber.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">64</span>&nbsp; <span class="chapter-title">API với Plumber</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./p07-10-shiny.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">65</span>&nbsp; <span class="chapter-title">Shiny apps</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./p10-02-deploy-shiny-app-aws.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">66</span>&nbsp; <span class="chapter-title">Deploy Shiny Apps lên AWS</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./p07-30-python-voi-r.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">67</span>&nbsp; <span class="chapter-title">Sử dụng Python với R</span></span></a>
  </div>
</li>
      </ul>
  </li>
        <li class="sidebar-item sidebar-item-section">
      <div class="sidebar-item-container"> 
            <a class="sidebar-item-text sidebar-link text-start" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-8" aria-expanded="true">
 <span class="menu-text">Kiến thức bổ trợ</span></a>
          <a class="sidebar-item-toggle text-start" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-8" aria-expanded="true" aria-label="Toggle section">
            <i class="bi bi-chevron-right ms-2"></i>
          </a> 
      </div>
      <ul id="quarto-sidebar-section-8" class="collapse list-unstyled sidebar-section depth1 show">  
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./p11-01-git.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">68</span>&nbsp; <span class="chapter-title">Sử dụng GIT</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./p11-02-cmd.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">69</span>&nbsp; <span class="chapter-title">CMD và Bash</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./p11-03-docker.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">70</span>&nbsp; <span class="chapter-title">Sử dụng docker</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./p11-04-apis.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">71</span>&nbsp; <span class="chapter-title">API</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./p11-90-other.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">72</span>&nbsp; <span class="chapter-title">Các tricks khác</span></span></a>
  </div>
</li>
      </ul>
  </li>
        <li class="sidebar-item sidebar-item-section">
      <div class="sidebar-item-container"> 
            <a class="sidebar-item-text sidebar-link text-start" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-9" aria-expanded="true">
 <span class="menu-text">Phân tích thực tế</span></a>
          <a class="sidebar-item-toggle text-start" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-9" aria-expanded="true" aria-label="Toggle section">
            <i class="bi bi-chevron-right ms-2"></i>
          </a> 
      </div>
      <ul id="quarto-sidebar-section-9" class="collapse list-unstyled sidebar-section depth1 show">  
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./p13-01-phan-tich-thuc-te.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">73</span>&nbsp; <span class="chapter-title">Các lưu ý phân tích thực tế</span></span></a>
  </div>
</li>
      </ul>
  </li>
    </ul>
    </div>
</nav>
<div id="quarto-sidebar-glass" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar,#quarto-sidebar-glass"></div>
<!-- margin-sidebar -->
    <div id="quarto-margin-sidebar" class="sidebar margin-sidebar">
        <nav id="TOC" role="doc-toc" class="toc-active">
    <h2 id="toc-title">Mục lục</h2>
   
  <ul>
  <li><a href="#giới-thiệu" id="toc-giới-thiệu" class="nav-link active" data-scroll-target="#giới-thiệu"><span class="header-section-number">25.1</span> Giới thiệu</a></li>
  <li><a href="#cài-đặt-và-khởi-động" id="toc-cài-đặt-và-khởi-động" class="nav-link" data-scroll-target="#cài-đặt-và-khởi-động"><span class="header-section-number">25.2</span> Cài đặt và khởi động</a></li>
  <li><a href="#thực-hành-với-r" id="toc-thực-hành-với-r" class="nav-link" data-scroll-target="#thực-hành-với-r"><span class="header-section-number">25.3</span> Thực hành với R</a>
  <ul>
  <li><a href="#lấy-dữ-liệu" id="toc-lấy-dữ-liệu" class="nav-link" data-scroll-target="#lấy-dữ-liệu"><span class="header-section-number">25.3.1</span> Lấy dữ liệu</a></li>
  <li><a href="#kiểm-tra-dữ-liệu" id="toc-kiểm-tra-dữ-liệu" class="nav-link" data-scroll-target="#kiểm-tra-dữ-liệu"><span class="header-section-number">25.3.2</span> Kiểm tra dữ liệu</a></li>
  <li><a href="#khởi-động-h2o" id="toc-khởi-động-h2o" class="nav-link" data-scroll-target="#khởi-động-h2o"><span class="header-section-number">25.3.3</span> Khởi động H2O</a></li>
  <li><a href="#đưa-dữ-liệu-vào-h2o" id="toc-đưa-dữ-liệu-vào-h2o" class="nav-link" data-scroll-target="#đưa-dữ-liệu-vào-h2o"><span class="header-section-number">25.3.4</span> Đưa dữ liệu vào H2O</a></li>
  <li><a href="#chia-dữ-liệu-traintest" id="toc-chia-dữ-liệu-traintest" class="nav-link" data-scroll-target="#chia-dữ-liệu-traintest"><span class="header-section-number">25.3.5</span> Chia dữ liệu train/test</a></li>
  <li><a href="#xây-dựng-mô-hình-trên-tập-train" id="toc-xây-dựng-mô-hình-trên-tập-train" class="nav-link" data-scroll-target="#xây-dựng-mô-hình-trên-tập-train"><span class="header-section-number">25.3.6</span> Xây dựng mô hình trên tập train</a></li>
  <li><a href="#dự-báo-trên-tập-test" id="toc-dự-báo-trên-tập-test" class="nav-link" data-scroll-target="#dự-báo-trên-tập-test"><span class="header-section-number">25.3.7</span> Dự báo trên tập test</a></li>
  <li><a href="#đánh-giá-chất-lượng-dự-báo-trên-test" id="toc-đánh-giá-chất-lượng-dự-báo-trên-test" class="nav-link" data-scroll-target="#đánh-giá-chất-lượng-dự-báo-trên-test"><span class="header-section-number">25.3.8</span> Đánh giá chất lượng dự báo trên test</a></li>
  <li><a href="#tuning" id="toc-tuning" class="nav-link" data-scroll-target="#tuning"><span class="header-section-number">25.3.9</span> Tuning</a></li>
  <li><a href="#lưu-và-load-mô-hình" id="toc-lưu-và-load-mô-hình" class="nav-link" data-scroll-target="#lưu-và-load-mô-hình"><span class="header-section-number">25.3.10</span> Lưu và load mô hình</a></li>
  </ul></li>
  <li><a href="#tìm-kiếm-mô-hình-tự-động" id="toc-tìm-kiếm-mô-hình-tự-động" class="nav-link" data-scroll-target="#tìm-kiếm-mô-hình-tự-động"><span class="header-section-number">25.4</span> Tìm kiếm mô hình tự động</a></li>
  <li><a href="#tài-liệu-tham-khảo" id="toc-tài-liệu-tham-khảo" class="nav-link" data-scroll-target="#tài-liệu-tham-khảo"><span class="header-section-number">25.5</span> Tài liệu tham khảo</a></li>
  </ul>
</nav>
    </div>
<!-- main -->
<main class="content" id="quarto-document-content">

<header id="title-block-header" class="quarto-title-block default">
<div class="quarto-title">
<h1 class="title"><span class="chapter-number">25</span>&nbsp; <span class="chapter-title">Xây dựng mô hình với H2O</span></h1>
</div>



<div class="quarto-title-meta">

    
  
    
  </div>
  

</header>

<section id="giới-thiệu" class="level2" data-number="25.1">
<h2 data-number="25.1" class="anchored" data-anchor-id="giới-thiệu"><span class="header-section-number">25.1</span> Giới thiệu</h2>
<ul>
<li>H2O là một phần mềm dựa trên nền tảng của Java dùng để mô hình hóa dữ liệu (data modeling) và tính toán nói chung.</li>
<li>H2O là một platform mã nguồn mở hàng đầu thế giới hiện nay về Machine Learning và AI.</li>
<li>Hỗ trợ nhiều phần mềm khác nhau như: R, Python, Azure, Spark…</li>
</ul>
</section>
<section id="cài-đặt-và-khởi-động" class="level2" data-number="25.2">
<h2 data-number="25.2" class="anchored" data-anchor-id="cài-đặt-và-khởi-động"><span class="header-section-number">25.2</span> Cài đặt và khởi động</h2>
<p>Để cài đặt và khởi động H2O, chúng ta cần thực hiện các bước sau:</p>
<ul>
<li><strong>Bước 1</strong>: Cài đặt Java</li>
</ul>
<div class="tabset-margin-container"></div><div class="panel-tabset">
<ul class="nav nav-tabs" role="tablist"><li class="nav-item" role="presentation"><a class="nav-link active" id="tabset-1-1-tab" data-bs-toggle="tab" data-bs-target="#tabset-1-1" role="tab" aria-controls="tabset-1-1" aria-selected="true" aria-current="page">Windows</a></li><li class="nav-item" role="presentation"><a class="nav-link" id="tabset-1-2-tab" data-bs-toggle="tab" data-bs-target="#tabset-1-2" role="tab" aria-controls="tabset-1-2" aria-selected="false">Ubuntu</a></li></ul>
<div class="tab-content">
<div id="tabset-1-1" class="tab-pane active" role="tabpanel" aria-labelledby="tabset-1-1-tab">
<ul>
<li>Download &amp; cài đặt Java <a href="">https://www.java.com/download/ie_manual.jsp</a></li>
</ul>
</div>
<div id="tabset-1-2" class="tab-pane" role="tabpanel" aria-labelledby="tabset-1-2-tab">
<p>Thực hiện câu lệnh sau</p>
<pre><code>sudo apt-get update
sudo apt install default-jdk</code></pre>
</div>
</div>
</div>
<ul>
<li><strong>Bước 2</strong>: Cài đặt R package <code>h2o</code></li>
</ul>
<div class="cell">
<div class="sourceCode cell-code" id="cb2"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb2-1"><a href="#cb2-1" aria-hidden="true" tabindex="-1"></a><span class="fu">install.packages</span>(<span class="st">"h2o"</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<ul>
<li><strong>Bước 3</strong>: Khởi động H2O từ R - sử dụng câu lệnh <code>h2o.init()</code></li>
</ul>
<div class="cell">
<div class="sourceCode cell-code" id="cb3"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb3-1"><a href="#cb3-1" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(h2o)</span>
<span id="cb3-2"><a href="#cb3-2" aria-hidden="true" tabindex="-1"></a><span class="fu">h2o.init</span>(<span class="at">ip =</span> <span class="st">"localhost"</span>, </span>
<span id="cb3-3"><a href="#cb3-3" aria-hidden="true" tabindex="-1"></a>         <span class="at">port =</span> <span class="dv">54321</span>, </span>
<span id="cb3-4"><a href="#cb3-4" aria-hidden="true" tabindex="-1"></a>         <span class="at">nthreads=</span> <span class="sc">-</span><span class="dv">1</span>,</span>
<span id="cb3-5"><a href="#cb3-5" aria-hidden="true" tabindex="-1"></a>         <span class="at">max_mem_size =</span> <span class="st">"4g"</span>) <span class="co"># Đặt mức RAM tối đa</span></span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code> Connection successful!

R is connected to the H2O cluster: 
    H2O cluster uptime:         21 minutes 19 seconds 
    H2O cluster timezone:       Etc/UTC 
    H2O data parsing timezone:  UTC 
    H2O cluster version:        3.42.0.2 
    H2O cluster version age:    6 months and 1 day 
    H2O cluster name:           H2O_started_from_R_jovyan_jew525 
    H2O cluster total nodes:    1 
    H2O cluster total memory:   3.97 GB 
    H2O cluster total cores:    2 
    H2O cluster allowed cores:  2 
    H2O cluster healthy:        TRUE 
    H2O Connection ip:          localhost 
    H2O Connection port:        54321 
    H2O Connection proxy:       NA 
    H2O Internal Security:      FALSE 
    R Version:                  R version 4.3.0 (2023-04-21) </code></pre>
</div>
</div>
<p><strong>Lưu ý</strong>: Trong trường hợp chúng ta muốn tắt H2O trên R, chúng ta có thể sử dụng câu lệnh sau:</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb5"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb5-1"><a href="#cb5-1" aria-hidden="true" tabindex="-1"></a><span class="fu">h2o.shutdown</span>(<span class="at">prompt =</span> T)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
</section>
<section id="thực-hành-với-r" class="level2" data-number="25.3">
<h2 data-number="25.3" class="anchored" data-anchor-id="thực-hành-với-r"><span class="header-section-number">25.3</span> Thực hành với R</h2>
<p>Để thực hành xây dựng mô hình dự báo với H2O, chúng ta sẽ sử dụng dữ liệu có sẵn trong <code>R</code> - <code>GermanCredit</code> trong package <strong>caret</strong>.</p>
<p>Đây là dữ liệu ghi nhận về lịch sử vay của khách hàng, với các 61 biến đầu vào cùng với biến đầu ra <code>Class</code> ghi nhận thực tế là các khoản vay đó có phải là khoản nợ xấu hay không. Chúng ta sẽ dự báo khoản vay nào không có nợ xấu.</p>
<section id="lấy-dữ-liệu" class="level3" data-number="25.3.1">
<h3 data-number="25.3.1" class="anchored" data-anchor-id="lấy-dữ-liệu"><span class="header-section-number">25.3.1</span> Lấy dữ liệu</h3>
<div class="cell">
<div class="sourceCode cell-code" id="cb6"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb6-1"><a href="#cb6-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Bước 1: Lấy dữ liệu</span></span>
<span id="cb6-2"><a href="#cb6-2" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(caret)</span>
<span id="cb6-3"><a href="#cb6-3" aria-hidden="true" tabindex="-1"></a><span class="fu">data</span>(<span class="st">"GermanCredit"</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
</section>
<section id="kiểm-tra-dữ-liệu" class="level3" data-number="25.3.2">
<h3 data-number="25.3.2" class="anchored" data-anchor-id="kiểm-tra-dữ-liệu"><span class="header-section-number">25.3.2</span> Kiểm tra dữ liệu</h3>
<div class="cell">
<div class="sourceCode cell-code" id="cb7"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb7-1"><a href="#cb7-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Bước 2: Kiểm tra dữ liệu</span></span>
<span id="cb7-2"><a href="#cb7-2" aria-hidden="true" tabindex="-1"></a><span class="co"># Kiểm tra định dạng các biến trong tập dữ liệu</span></span>
<span id="cb7-3"><a href="#cb7-3" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(dplyr)</span>
<span id="cb7-4"><a href="#cb7-4" aria-hidden="true" tabindex="-1"></a>GermanCredit <span class="sc">%&gt;%</span> str</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>'data.frame':   1000 obs. of  62 variables:
 $ Duration                              : int  6 48 12 42 24 36 24 36 12 30 ...
 $ Amount                                : int  1169 5951 2096 7882 4870 9055 2835 6948 3059 5234 ...
 $ InstallmentRatePercentage             : int  4 2 2 2 3 2 3 2 2 4 ...
 $ ResidenceDuration                     : int  4 2 3 4 4 4 4 2 4 2 ...
 $ Age                                   : int  67 22 49 45 53 35 53 35 61 28 ...
 $ NumberExistingCredits                 : int  2 1 1 1 2 1 1 1 1 2 ...
 $ NumberPeopleMaintenance               : int  1 1 2 2 2 2 1 1 1 1 ...
 $ Telephone                             : num  0 1 1 1 1 0 1 0 1 1 ...
 $ ForeignWorker                         : num  1 1 1 1 1 1 1 1 1 1 ...
 $ Class                                 : Factor w/ 2 levels "Bad","Good": 2 1 2 2 1 2 2 2 2 1 ...
 $ CheckingAccountStatus.lt.0            : num  1 0 0 1 1 0 0 0 0 0 ...
 $ CheckingAccountStatus.0.to.200        : num  0 1 0 0 0 0 0 1 0 1 ...
 $ CheckingAccountStatus.gt.200          : num  0 0 0 0 0 0 0 0 0 0 ...
 $ CheckingAccountStatus.none            : num  0 0 1 0 0 1 1 0 1 0 ...
 $ CreditHistory.NoCredit.AllPaid        : num  0 0 0 0 0 0 0 0 0 0 ...
 $ CreditHistory.ThisBank.AllPaid        : num  0 0 0 0 0 0 0 0 0 0 ...
 $ CreditHistory.PaidDuly                : num  0 1 0 1 0 1 1 1 1 0 ...
 $ CreditHistory.Delay                   : num  0 0 0 0 1 0 0 0 0 0 ...
 $ CreditHistory.Critical                : num  1 0 1 0 0 0 0 0 0 1 ...
 $ Purpose.NewCar                        : num  0 0 0 0 1 0 0 0 0 1 ...
 $ Purpose.UsedCar                       : num  0 0 0 0 0 0 0 1 0 0 ...
 $ Purpose.Furniture.Equipment           : num  0 0 0 1 0 0 1 0 0 0 ...
 $ Purpose.Radio.Television              : num  1 1 0 0 0 0 0 0 1 0 ...
 $ Purpose.DomesticAppliance             : num  0 0 0 0 0 0 0 0 0 0 ...
 $ Purpose.Repairs                       : num  0 0 0 0 0 0 0 0 0 0 ...
 $ Purpose.Education                     : num  0 0 1 0 0 1 0 0 0 0 ...
 $ Purpose.Vacation                      : num  0 0 0 0 0 0 0 0 0 0 ...
 $ Purpose.Retraining                    : num  0 0 0 0 0 0 0 0 0 0 ...
 $ Purpose.Business                      : num  0 0 0 0 0 0 0 0 0 0 ...
 $ Purpose.Other                         : num  0 0 0 0 0 0 0 0 0 0 ...
 $ SavingsAccountBonds.lt.100            : num  0 1 1 1 1 0 0 1 0 1 ...
 $ SavingsAccountBonds.100.to.500        : num  0 0 0 0 0 0 0 0 0 0 ...
 $ SavingsAccountBonds.500.to.1000       : num  0 0 0 0 0 0 1 0 0 0 ...
 $ SavingsAccountBonds.gt.1000           : num  0 0 0 0 0 0 0 0 1 0 ...
 $ SavingsAccountBonds.Unknown           : num  1 0 0 0 0 1 0 0 0 0 ...
 $ EmploymentDuration.lt.1               : num  0 0 0 0 0 0 0 0 0 0 ...
 $ EmploymentDuration.1.to.4             : num  0 1 0 0 1 1 0 1 0 0 ...
 $ EmploymentDuration.4.to.7             : num  0 0 1 1 0 0 0 0 1 0 ...
 $ EmploymentDuration.gt.7               : num  1 0 0 0 0 0 1 0 0 0 ...
 $ EmploymentDuration.Unemployed         : num  0 0 0 0 0 0 0 0 0 1 ...
 $ Personal.Male.Divorced.Seperated      : num  0 0 0 0 0 0 0 0 1 0 ...
 $ Personal.Female.NotSingle             : num  0 1 0 0 0 0 0 0 0 0 ...
 $ Personal.Male.Single                  : num  1 0 1 1 1 1 1 1 0 0 ...
 $ Personal.Male.Married.Widowed         : num  0 0 0 0 0 0 0 0 0 1 ...
 $ Personal.Female.Single                : num  0 0 0 0 0 0 0 0 0 0 ...
 $ OtherDebtorsGuarantors.None           : num  1 1 1 0 1 1 1 1 1 1 ...
 $ OtherDebtorsGuarantors.CoApplicant    : num  0 0 0 0 0 0 0 0 0 0 ...
 $ OtherDebtorsGuarantors.Guarantor      : num  0 0 0 1 0 0 0 0 0 0 ...
 $ Property.RealEstate                   : num  1 1 1 0 0 0 0 0 1 0 ...
 $ Property.Insurance                    : num  0 0 0 1 0 0 1 0 0 0 ...
 $ Property.CarOther                     : num  0 0 0 0 0 0 0 1 0 1 ...
 $ Property.Unknown                      : num  0 0 0 0 1 1 0 0 0 0 ...
 $ OtherInstallmentPlans.Bank            : num  0 0 0 0 0 0 0 0 0 0 ...
 $ OtherInstallmentPlans.Stores          : num  0 0 0 0 0 0 0 0 0 0 ...
 $ OtherInstallmentPlans.None            : num  1 1 1 1 1 1 1 1 1 1 ...
 $ Housing.Rent                          : num  0 0 0 0 0 0 0 1 0 0 ...
 $ Housing.Own                           : num  1 1 1 0 0 0 1 0 1 1 ...
 $ Housing.ForFree                       : num  0 0 0 1 1 1 0 0 0 0 ...
 $ Job.UnemployedUnskilled               : num  0 0 0 0 0 0 0 0 0 0 ...
 $ Job.UnskilledResident                 : num  0 0 1 0 0 1 0 0 1 0 ...
 $ Job.SkilledEmployee                   : num  1 1 0 1 1 0 1 0 0 0 ...
 $ Job.Management.SelfEmp.HighlyQualified: num  0 0 0 0 0 0 0 1 0 1 ...</code></pre>
</div>
<div class="sourceCode cell-code" id="cb9"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb9-1"><a href="#cb9-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Kiểm tra biến đầu ra (biến muốn dự báo)</span></span>
<span id="cb9-2"><a href="#cb9-2" aria-hidden="true" tabindex="-1"></a>GermanCredit<span class="sc">$</span>Class <span class="sc">%&gt;%</span> </span>
<span id="cb9-3"><a href="#cb9-3" aria-hidden="true" tabindex="-1"></a>  table <span class="sc">%&gt;%</span> </span>
<span id="cb9-4"><a href="#cb9-4" aria-hidden="true" tabindex="-1"></a>  prop.table</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>.
 Bad Good 
 0.3  0.7 </code></pre>
</div>
</div>
<p>Như vậy, chúng ta thấy trong tập dữ liệu này:</p>
<ul>
<li>70% là các khoản vay không có nợ xấu</li>
<li>30% là các khoản vay có nợ xấu</li>
</ul>
</section>
<section id="khởi-động-h2o" class="level3" data-number="25.3.3">
<h3 data-number="25.3.3" class="anchored" data-anchor-id="khởi-động-h2o"><span class="header-section-number">25.3.3</span> Khởi động H2O</h3>
<div class="cell">
<div class="sourceCode cell-code" id="cb11"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb11-1"><a href="#cb11-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Bước 3: Khởi động H2O</span></span>
<span id="cb11-2"><a href="#cb11-2" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(h2o)</span>
<span id="cb11-3"><a href="#cb11-3" aria-hidden="true" tabindex="-1"></a><span class="fu">h2o.init</span>(<span class="at">ip =</span> <span class="st">"localhost"</span>, </span>
<span id="cb11-4"><a href="#cb11-4" aria-hidden="true" tabindex="-1"></a>         <span class="at">port =</span> <span class="dv">54321</span>, </span>
<span id="cb11-5"><a href="#cb11-5" aria-hidden="true" tabindex="-1"></a>         <span class="at">nthreads=</span> <span class="sc">-</span><span class="dv">1</span>,</span>
<span id="cb11-6"><a href="#cb11-6" aria-hidden="true" tabindex="-1"></a>         <span class="at">max_mem_size =</span> <span class="st">"4g"</span>) <span class="co"># Đặt mức RAM tối đa</span></span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code> Connection successful!

R is connected to the H2O cluster: 
    H2O cluster uptime:         21 minutes 20 seconds 
    H2O cluster timezone:       Etc/UTC 
    H2O data parsing timezone:  UTC 
    H2O cluster version:        3.42.0.2 
    H2O cluster version age:    6 months and 1 day 
    H2O cluster name:           H2O_started_from_R_jovyan_jew525 
    H2O cluster total nodes:    1 
    H2O cluster total memory:   3.97 GB 
    H2O cluster total cores:    2 
    H2O cluster allowed cores:  2 
    H2O cluster healthy:        TRUE 
    H2O Connection ip:          localhost 
    H2O Connection port:        54321 
    H2O Connection proxy:       NA 
    H2O Internal Security:      FALSE 
    R Version:                  R version 4.3.0 (2023-04-21) </code></pre>
</div>
</div>
</section>
<section id="đưa-dữ-liệu-vào-h2o" class="level3" data-number="25.3.4">
<h3 data-number="25.3.4" class="anchored" data-anchor-id="đưa-dữ-liệu-vào-h2o"><span class="header-section-number">25.3.4</span> Đưa dữ liệu vào H2O</h3>
<p>Để đưa dữ liệu vào H2O, chúng ta sử dụng câu lệnh: <code>as.h2o()</code>.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb13"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb13-1"><a href="#cb13-1" aria-hidden="true" tabindex="-1"></a>GermanCredit <span class="sc">%&gt;%</span> head</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>  Duration Amount InstallmentRatePercentage ResidenceDuration Age
1        6   1169                         4                 4  67
2       48   5951                         2                 2  22
3       12   2096                         2                 3  49
4       42   7882                         2                 4  45
5       24   4870                         3                 4  53
6       36   9055                         2                 4  35
  NumberExistingCredits NumberPeopleMaintenance Telephone ForeignWorker Class
1                     2                       1         0             1  Good
2                     1                       1         1             1   Bad
3                     1                       2         1             1  Good
4                     1                       2         1             1  Good
5                     2                       2         1             1   Bad
6                     1                       2         0             1  Good
  CheckingAccountStatus.lt.0 CheckingAccountStatus.0.to.200
1                          1                              0
2                          0                              1
3                          0                              0
4                          1                              0
5                          1                              0
6                          0                              0
  CheckingAccountStatus.gt.200 CheckingAccountStatus.none
1                            0                          0
2                            0                          0
3                            0                          1
4                            0                          0
5                            0                          0
6                            0                          1
  CreditHistory.NoCredit.AllPaid CreditHistory.ThisBank.AllPaid
1                              0                              0
2                              0                              0
3                              0                              0
4                              0                              0
5                              0                              0
6                              0                              0
  CreditHistory.PaidDuly CreditHistory.Delay CreditHistory.Critical
1                      0                   0                      1
2                      1                   0                      0
3                      0                   0                      1
4                      1                   0                      0
5                      0                   1                      0
6                      1                   0                      0
  Purpose.NewCar Purpose.UsedCar Purpose.Furniture.Equipment
1              0               0                           0
2              0               0                           0
3              0               0                           0
4              0               0                           1
5              1               0                           0
6              0               0                           0
  Purpose.Radio.Television Purpose.DomesticAppliance Purpose.Repairs
1                        1                         0               0
2                        1                         0               0
3                        0                         0               0
4                        0                         0               0
5                        0                         0               0
6                        0                         0               0
  Purpose.Education Purpose.Vacation Purpose.Retraining Purpose.Business
1                 0                0                  0                0
2                 0                0                  0                0
3                 1                0                  0                0
4                 0                0                  0                0
5                 0                0                  0                0
6                 1                0                  0                0
  Purpose.Other SavingsAccountBonds.lt.100 SavingsAccountBonds.100.to.500
1             0                          0                              0
2             0                          1                              0
3             0                          1                              0
4             0                          1                              0
5             0                          1                              0
6             0                          0                              0
  SavingsAccountBonds.500.to.1000 SavingsAccountBonds.gt.1000
1                               0                           0
2                               0                           0
3                               0                           0
4                               0                           0
5                               0                           0
6                               0                           0
  SavingsAccountBonds.Unknown EmploymentDuration.lt.1 EmploymentDuration.1.to.4
1                           1                       0                         0
2                           0                       0                         1
3                           0                       0                         0
4                           0                       0                         0
5                           0                       0                         1
6                           1                       0                         1
  EmploymentDuration.4.to.7 EmploymentDuration.gt.7
1                         0                       1
2                         0                       0
3                         1                       0
4                         1                       0
5                         0                       0
6                         0                       0
  EmploymentDuration.Unemployed Personal.Male.Divorced.Seperated
1                             0                                0
2                             0                                0
3                             0                                0
4                             0                                0
5                             0                                0
6                             0                                0
  Personal.Female.NotSingle Personal.Male.Single Personal.Male.Married.Widowed
1                         0                    1                             0
2                         1                    0                             0
3                         0                    1                             0
4                         0                    1                             0
5                         0                    1                             0
6                         0                    1                             0
  Personal.Female.Single OtherDebtorsGuarantors.None
1                      0                           1
2                      0                           1
3                      0                           1
4                      0                           0
5                      0                           1
6                      0                           1
  OtherDebtorsGuarantors.CoApplicant OtherDebtorsGuarantors.Guarantor
1                                  0                                0
2                                  0                                0
3                                  0                                0
4                                  0                                1
5                                  0                                0
6                                  0                                0
  Property.RealEstate Property.Insurance Property.CarOther Property.Unknown
1                   1                  0                 0                0
2                   1                  0                 0                0
3                   1                  0                 0                0
4                   0                  1                 0                0
5                   0                  0                 0                1
6                   0                  0                 0                1
  OtherInstallmentPlans.Bank OtherInstallmentPlans.Stores
1                          0                            0
2                          0                            0
3                          0                            0
4                          0                            0
5                          0                            0
6                          0                            0
  OtherInstallmentPlans.None Housing.Rent Housing.Own Housing.ForFree
1                          1            0           1               0
2                          1            0           1               0
3                          1            0           1               0
4                          1            0           0               1
5                          1            0           0               1
6                          1            0           0               1
  Job.UnemployedUnskilled Job.UnskilledResident Job.SkilledEmployee
1                       0                     0                   1
2                       0                     0                   1
3                       0                     1                   0
4                       0                     0                   1
5                       0                     0                   1
6                       0                     1                   0
  Job.Management.SelfEmp.HighlyQualified
1                                      0
2                                      0
3                                      0
4                                      0
5                                      0
6                                      0</code></pre>
</div>
<div class="sourceCode cell-code" id="cb15"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb15-1"><a href="#cb15-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Bước 4: Đưa dữ liệu vào h2o</span></span>
<span id="cb15-2"><a href="#cb15-2" aria-hidden="true" tabindex="-1"></a>data_h2o <span class="ot">&lt;-</span> <span class="fu">as.h2o</span>(GermanCredit)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>
  |                                                                            
  |                                                                      |   0%
  |                                                                            
  |======================================================================| 100%</code></pre>
</div>
</div>
</section>
<section id="chia-dữ-liệu-traintest" class="level3" data-number="25.3.5">
<h3 data-number="25.3.5" class="anchored" data-anchor-id="chia-dữ-liệu-traintest"><span class="header-section-number">25.3.5</span> Chia dữ liệu train/test</h3>
<p>Chia tập dữ liệu thành 2 tập dữ liệu train và test (tỷ lệ 80-20)</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb17"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb17-1"><a href="#cb17-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Bước 5: Chia tập dữ liệu thành: train/test (tỷ lệ 80/20) </span></span>
<span id="cb17-2"><a href="#cb17-2" aria-hidden="true" tabindex="-1"></a><span class="fu">set.seed</span>(<span class="dv">1234</span>)</span>
<span id="cb17-3"><a href="#cb17-3" aria-hidden="true" tabindex="-1"></a>data_split <span class="ot">=</span> <span class="fu">h2o.splitFrame</span>(<span class="at">data =</span> data_h2o, </span>
<span id="cb17-4"><a href="#cb17-4" aria-hidden="true" tabindex="-1"></a>                            <span class="at">ratios =</span> <span class="fl">0.8</span>)</span>
<span id="cb17-5"><a href="#cb17-5" aria-hidden="true" tabindex="-1"></a>train <span class="ot">=</span> data_split[[<span class="dv">1</span>]]</span>
<span id="cb17-6"><a href="#cb17-6" aria-hidden="true" tabindex="-1"></a>test <span class="ot">=</span> data_split[[<span class="dv">2</span>]]</span>
<span id="cb17-7"><a href="#cb17-7" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb17-8"><a href="#cb17-8" aria-hidden="true" tabindex="-1"></a><span class="co"># Tập dữ liệu train (data frame)</span></span>
<span id="cb17-9"><a href="#cb17-9" aria-hidden="true" tabindex="-1"></a>train_df <span class="ot">&lt;-</span> <span class="fu">as.data.frame</span>(train)</span>
<span id="cb17-10"><a href="#cb17-10" aria-hidden="true" tabindex="-1"></a>train_df<span class="sc">$</span>Class <span class="sc">%&gt;%</span> table</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>.
 Bad Good 
 235  551 </code></pre>
</div>
<div class="sourceCode cell-code" id="cb19"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb19-1"><a href="#cb19-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Tập dữ liệu test (data frame)</span></span>
<span id="cb19-2"><a href="#cb19-2" aria-hidden="true" tabindex="-1"></a>test_df <span class="ot">&lt;-</span> <span class="fu">as.data.frame</span>(test)</span>
<span id="cb19-3"><a href="#cb19-3" aria-hidden="true" tabindex="-1"></a>test_df<span class="sc">$</span>Status <span class="sc">%&gt;%</span> table</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>&lt; table of extent 0 &gt;</code></pre>
</div>
</div>
</section>
<section id="xây-dựng-mô-hình-trên-tập-train" class="level3" data-number="25.3.6">
<h3 data-number="25.3.6" class="anchored" data-anchor-id="xây-dựng-mô-hình-trên-tập-train"><span class="header-section-number">25.3.6</span> Xây dựng mô hình trên tập train</h3>
<p>Để xây dựng mô hình dự báo với H2O, chúng ta có thể sử dụng những câu lệnh khác nhau tương ứng với từng phương pháp/thuật toán như: Logistic regression, Random Forests, Boosting…</p>
<ul>
<li><code>h2o.glm()</code> - Logistic regression</li>
<li><code>h2o.randomForest()</code> - Random Forests</li>
<li><code>h2o.gbm()</code> - Boosting</li>
</ul>
<div class="cell">
<div class="sourceCode cell-code" id="cb21"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb21-1"><a href="#cb21-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Bước 6: Xây dựng mô hình trên train</span></span>
<span id="cb21-2"><a href="#cb21-2" aria-hidden="true" tabindex="-1"></a>start_time <span class="ot">&lt;-</span> <span class="fu">Sys.time</span>()</span>
<span id="cb21-3"><a href="#cb21-3" aria-hidden="true" tabindex="-1"></a><span class="fu">set.seed</span>(<span class="dv">1</span>)</span>
<span id="cb21-4"><a href="#cb21-4" aria-hidden="true" tabindex="-1"></a>gbm_model1 <span class="ot">&lt;-</span> <span class="fu">h2o.gbm</span>(<span class="at">training_frame =</span> train, <span class="co"># Tập dữ liệu train</span></span>
<span id="cb21-5"><a href="#cb21-5" aria-hidden="true" tabindex="-1"></a>                      <span class="at">x =</span> <span class="fu">setdiff</span>(<span class="fu">names</span>(GermanCredit), <span class="st">"Class"</span>),  <span class="co"># Các biến đầu vào</span></span>
<span id="cb21-6"><a href="#cb21-6" aria-hidden="true" tabindex="-1"></a>                      <span class="at">y =</span> <span class="st">"Class"</span> <span class="co"># Biến đầu ra (biến muốn dự báo)</span></span>
<span id="cb21-7"><a href="#cb21-7" aria-hidden="true" tabindex="-1"></a>                      )</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>
  |                                                                            
  |                                                                      |   0%
  |                                                                            
  |======================================================================| 100%</code></pre>
</div>
<div class="sourceCode cell-code" id="cb23"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb23-1"><a href="#cb23-1" aria-hidden="true" tabindex="-1"></a>end_time <span class="ot">&lt;-</span> <span class="fu">Sys.time</span>()</span>
<span id="cb23-2"><a href="#cb23-2" aria-hidden="true" tabindex="-1"></a>time <span class="ot">&lt;-</span> end_time <span class="sc">-</span> start_time</span>
<span id="cb23-3"><a href="#cb23-3" aria-hidden="true" tabindex="-1"></a>time</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>Time difference of 1.127262 secs</code></pre>
</div>
</div>
<p>Chúng ta thấy việc xây dựng mô hình với H2O có tốc độ rất nhanh, xây dựng mô hình với các tham số cơ bản với dữ liệu này chỉ mất khoảng 1.13 giây. Đương nhiên trong trường hợp này dữ liệu nhỏ nên chúng ta chưa nhìn thấy rõ ưu điểm vượt trội của H2O về tốc độ, nhưng trong trường hơp dữ liệu lớn, việc sử dụng H2O sẽ rút ngắn thời gian xây dựng mô hình dự báo của chúng ta đi rất nhiều.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb25"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb25-1"><a href="#cb25-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Summary model</span></span>
<span id="cb25-2"><a href="#cb25-2" aria-hidden="true" tabindex="-1"></a>gbm_model1 <span class="sc">%&gt;%</span> summary</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>Model Details:
==============

H2OBinomialModel: gbm
Model Key:  GBM_model_R_1706352094610_5793 
Model Summary: 
  number_of_trees number_of_internal_trees model_size_in_bytes min_depth
1              50                       50               13980         5
  max_depth mean_depth min_leaves max_leaves mean_leaves
1         5    5.00000          9         26    17.58000

H2OBinomialMetrics: gbm
** Reported on training data. **

MSE:  0.07258735
RMSE:  0.2694204
LogLoss:  0.2676266
Mean Per-Class Error:  0.07134031
AUC:  0.9794455
AUCPR:  0.990769
Gini:  0.958891
R^2:  0.6536728

Confusion Matrix (vertical: actual; across: predicted) for F1-optimal threshold:
       Bad Good    Error     Rate
Bad    210   25 0.106383  =25/235
Good    20  531 0.036298  =20/551
Totals 230  556 0.057252  =45/786

Maximum Metrics: Maximum metrics at their respective thresholds
                        metric threshold      value idx
1                       max f1  0.585928   0.959350 231
2                       max f2  0.528659   0.973467 251
3                 max f0point5  0.641146   0.964326 215
4                 max accuracy  0.585928   0.942748 231
5                max precision  0.985738   1.000000   0
6                   max recall  0.301839   1.000000 324
7              max specificity  0.985738   1.000000   0
8             max absolute_mcc  0.585928   0.862683 231
9   max min_per_class_accuracy  0.650274   0.932849 211
10 max mean_per_class_accuracy  0.641146   0.936919 215
11                     max tns  0.985738 235.000000   0
12                     max fns  0.985738 550.000000   0
13                     max fps  0.050169 235.000000 399
14                     max tps  0.301839 551.000000 324
15                     max tnr  0.985738   1.000000   0
16                     max fnr  0.985738   0.998185   0
17                     max fpr  0.050169   1.000000 399
18                     max tpr  0.301839   1.000000 324

Gains/Lift Table: Extract with `h2o.gainsLift(&lt;model&gt;, &lt;data&gt;)` or `h2o.gainsLift(&lt;model&gt;, valid=&lt;T/F&gt;, xval=&lt;T/F&gt;)`



Scoring History: 
            timestamp   duration number_of_trees training_rmse training_logloss
1 2024-01-27 11:02:58  0.003 sec               0       0.45781          0.61000
2 2024-01-27 11:02:58  0.025 sec               1       0.44489          0.58254
3 2024-01-27 11:02:58  0.047 sec               2       0.43324          0.55877
4 2024-01-27 11:02:58  0.066 sec               3       0.42313          0.53861
5 2024-01-27 11:02:58  0.085 sec               4       0.41501          0.52240
  training_auc training_pr_auc training_lift training_classification_error
1      0.50000         0.70102       1.00000                       0.29898
2      0.82314         0.91958       1.42650                       0.22774
3      0.83729         0.92585       1.42650                       0.21374
4      0.85373         0.93406       1.42650                       0.20738
5      0.86354         0.93792       1.42650                       0.19338

---
             timestamp   duration number_of_trees training_rmse
46 2024-01-27 11:02:59  0.721 sec              45       0.27706
47 2024-01-27 11:02:59  0.733 sec              46       0.27555
48 2024-01-27 11:02:59  0.745 sec              47       0.27383
49 2024-01-27 11:02:59  0.786 sec              48       0.27225
50 2024-01-27 11:02:59  0.805 sec              49       0.27105
51 2024-01-27 11:02:59  0.830 sec              50       0.26942
   training_logloss training_auc training_pr_auc training_lift
46          0.27988      0.97668         0.98933       1.42650
47          0.27727      0.97715         0.98965       1.42650
48          0.27464      0.97787         0.99002       1.42650
49          0.27199      0.97879         0.99049       1.42650
50          0.27012      0.97924         0.99069       1.42650
51          0.26763      0.97945         0.99077       1.42650
   training_classification_error
46                       0.06234
47                       0.06107
48                       0.05980
49                       0.05980
50                       0.05852
51                       0.05725

Variable Importances: (Extract with `h2o.varimp`) 
=================================================

Variable Importances: 
                    variable relative_importance scaled_importance percentage
1 CheckingAccountStatus.none           84.350624          1.000000   0.156410
2                     Amount           82.419136          0.977102   0.152829
3                   Duration           68.733696          0.814857   0.127452
4                        Age           31.725632          0.376116   0.058828
5             Purpose.NewCar           19.282278          0.228597   0.035755

---
                           variable relative_importance scaled_importance
54                  Housing.ForFree            0.132180          0.001567
55        Purpose.DomesticAppliance            0.000000          0.000000
56               Purpose.Retraining            0.000000          0.000000
57                    Purpose.Other            0.000000          0.000000
58 Personal.Male.Divorced.Seperated            0.000000          0.000000
59          Job.UnemployedUnskilled            0.000000          0.000000
   percentage
54   0.000245
55   0.000000
56   0.000000
57   0.000000
58   0.000000
59   0.000000</code></pre>
</div>
</div>
<p>Nhìn vào kết quả mô hình vừa được xây dựng trên tập train, chúng ta có thể thấy một số thông tin quan trọng sau:</p>
<ul>
<li>Các tham số (<code>parameters</code>) cơ bản của mô hình:
<ul>
<li><code>number_of_trees</code> = 50: Số lượng cây là 50</li>
<li><code>max_depth</code> = 5: Mỗi cây có 5 tầng (mức độ phức tạp của mô hình)</li>
</ul></li>
<li>AUC trên tập train: 0.97</li>
<li>Dựa vào mục <code>Confusion Matrix</code> (tối ưu hóa F1-score) có thể tính toán được:
<ul>
<li><code>error rate</code> (tỷ lệ quan sát dự báo sai): 45/786 = 0.057 (5.7%)</li>
<li><code>accuracy</code> (tỷ lệ quan sát dự báo đúng): 1 - 0.057 = 0.943 (94.3%)</li>
<li><code>precision</code>: 531/551 = 0.96 (96%)</li>
<li><code>recall</code>: 531/556 = 0.96 (96%)</li>
</ul></li>
<li>Dựa vào mục <code>Maximum Metrics</code>, chúng ta có thể biết được các ngưỡng cutoff xác suất để tối ưu hóa các chỉ số như accuracy, precision, recall, f1-score…
<ul>
<li><code>max f1</code>: Điểm cutoff xác suất là 0.585928</li>
<li><code>max accuracy</code>: 0.585928</li>
<li><code>max recall</code>: 0.301839</li>
<li><code>max precision</code>: 0.985738</li>
</ul></li>
<li>Dựa vào mục <code>Variable Importances</code>, chúng ta có thể biết được những biến nào có ảnh hưởng nhiều nhất đến biến đầu ra mà chúng ta muốn dự báo (có thể sử dụng câu lệnh <code>h2o.varimp()</code> để xem chi tiết). Trong trường hợp này, các biến có ảnh hưởng nhiều nhất tới biến <code>Class</code> theo thứ tự là:
<ul>
<li>CheckingAccountStatus.none</li>
<li>Amount</li>
<li>Duration</li>
<li>Age</li>
<li>Purpose.NewCar</li>
</ul></li>
</ul>
<div class="cell">
<div class="sourceCode cell-code" id="cb27"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb27-1"><a href="#cb27-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Kiểm tra chi tiết các biến có ảnh hướng nhiều tới biến dự báo trong mô hình</span></span>
<span id="cb27-2"><a href="#cb27-2" aria-hidden="true" tabindex="-1"></a>gbm_model1 <span class="sc">%&gt;%</span> </span>
<span id="cb27-3"><a href="#cb27-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">h2o.varimp</span>() <span class="sc">%&gt;%</span> </span>
<span id="cb27-4"><a href="#cb27-4" aria-hidden="true" tabindex="-1"></a>  as.data.frame <span class="sc">%&gt;%</span> </span>
<span id="cb27-5"><a href="#cb27-5" aria-hidden="true" tabindex="-1"></a>  knitr<span class="sc">::</span><span class="fu">kable</span>()</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<table class="table table-sm table-striped small">
<colgroup>
<col style="width: 44%">
<col style="width: 22%">
<col style="width: 20%">
<col style="width: 12%">
</colgroup>
<thead>
<tr class="header">
<th style="text-align: left;">variable</th>
<th style="text-align: right;">relative_importance</th>
<th style="text-align: right;">scaled_importance</th>
<th style="text-align: right;">percentage</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td style="text-align: left;">CheckingAccountStatus.none</td>
<td style="text-align: right;">84.3506241</td>
<td style="text-align: right;">1.0000000</td>
<td style="text-align: right;">0.1564102</td>
</tr>
<tr class="even">
<td style="text-align: left;">Amount</td>
<td style="text-align: right;">82.4191360</td>
<td style="text-align: right;">0.9771017</td>
<td style="text-align: right;">0.1528287</td>
</tr>
<tr class="odd">
<td style="text-align: left;">Duration</td>
<td style="text-align: right;">68.7336960</td>
<td style="text-align: right;">0.8148570</td>
<td style="text-align: right;">0.1274520</td>
</tr>
<tr class="even">
<td style="text-align: left;">Age</td>
<td style="text-align: right;">31.7256317</td>
<td style="text-align: right;">0.3761161</td>
<td style="text-align: right;">0.0588284</td>
</tr>
<tr class="odd">
<td style="text-align: left;">Purpose.NewCar</td>
<td style="text-align: right;">19.2822781</td>
<td style="text-align: right;">0.2285967</td>
<td style="text-align: right;">0.0357549</td>
</tr>
<tr class="even">
<td style="text-align: left;">InstallmentRatePercentage</td>
<td style="text-align: right;">15.5161829</td>
<td style="text-align: right;">0.1839486</td>
<td style="text-align: right;">0.0287714</td>
</tr>
<tr class="odd">
<td style="text-align: left;">OtherInstallmentPlans.None</td>
<td style="text-align: right;">15.2438316</td>
<td style="text-align: right;">0.1807198</td>
<td style="text-align: right;">0.0282664</td>
</tr>
<tr class="even">
<td style="text-align: left;">CreditHistory.Critical</td>
<td style="text-align: right;">14.5524130</td>
<td style="text-align: right;">0.1725229</td>
<td style="text-align: right;">0.0269843</td>
</tr>
<tr class="odd">
<td style="text-align: left;">CheckingAccountStatus.lt.0</td>
<td style="text-align: right;">12.5769672</td>
<td style="text-align: right;">0.1491034</td>
<td style="text-align: right;">0.0233213</td>
</tr>
<tr class="even">
<td style="text-align: left;">Property.RealEstate</td>
<td style="text-align: right;">12.3567972</td>
<td style="text-align: right;">0.1464933</td>
<td style="text-align: right;">0.0229130</td>
</tr>
<tr class="odd">
<td style="text-align: left;">SavingsAccountBonds.lt.100</td>
<td style="text-align: right;">10.7499561</td>
<td style="text-align: right;">0.1274437</td>
<td style="text-align: right;">0.0199335</td>
</tr>
<tr class="even">
<td style="text-align: left;">OtherDebtorsGuarantors.Guarantor</td>
<td style="text-align: right;">9.6545200</td>
<td style="text-align: right;">0.1144570</td>
<td style="text-align: right;">0.0179022</td>
</tr>
<tr class="odd">
<td style="text-align: left;">Property.Insurance</td>
<td style="text-align: right;">9.3979931</td>
<td style="text-align: right;">0.1114158</td>
<td style="text-align: right;">0.0174266</td>
</tr>
<tr class="even">
<td style="text-align: left;">Job.SkilledEmployee</td>
<td style="text-align: right;">8.7692375</td>
<td style="text-align: right;">0.1039617</td>
<td style="text-align: right;">0.0162607</td>
</tr>
<tr class="odd">
<td style="text-align: left;">CheckingAccountStatus.gt.200</td>
<td style="text-align: right;">8.7212677</td>
<td style="text-align: right;">0.1033930</td>
<td style="text-align: right;">0.0161717</td>
</tr>
<tr class="even">
<td style="text-align: left;">ResidenceDuration</td>
<td style="text-align: right;">8.4237700</td>
<td style="text-align: right;">0.0998661</td>
<td style="text-align: right;">0.0156201</td>
</tr>
<tr class="odd">
<td style="text-align: left;">OtherDebtorsGuarantors.None</td>
<td style="text-align: right;">7.9725552</td>
<td style="text-align: right;">0.0945168</td>
<td style="text-align: right;">0.0147834</td>
</tr>
<tr class="even">
<td style="text-align: left;">OtherInstallmentPlans.Bank</td>
<td style="text-align: right;">7.7707009</td>
<td style="text-align: right;">0.0921238</td>
<td style="text-align: right;">0.0144091</td>
</tr>
<tr class="odd">
<td style="text-align: left;">CreditHistory.NoCredit.AllPaid</td>
<td style="text-align: right;">7.2156229</td>
<td style="text-align: right;">0.0855432</td>
<td style="text-align: right;">0.0133798</td>
</tr>
<tr class="even">
<td style="text-align: left;">Personal.Male.Single</td>
<td style="text-align: right;">7.0852146</td>
<td style="text-align: right;">0.0839972</td>
<td style="text-align: right;">0.0131380</td>
</tr>
<tr class="odd">
<td style="text-align: left;">NumberExistingCredits</td>
<td style="text-align: right;">6.5925212</td>
<td style="text-align: right;">0.0781562</td>
<td style="text-align: right;">0.0122244</td>
</tr>
<tr class="even">
<td style="text-align: left;">Purpose.UsedCar</td>
<td style="text-align: right;">6.2361321</td>
<td style="text-align: right;">0.0739311</td>
<td style="text-align: right;">0.0115636</td>
</tr>
<tr class="odd">
<td style="text-align: left;">Personal.Female.NotSingle</td>
<td style="text-align: right;">5.6832266</td>
<td style="text-align: right;">0.0673762</td>
<td style="text-align: right;">0.0105383</td>
</tr>
<tr class="even">
<td style="text-align: left;">EmploymentDuration.lt.1</td>
<td style="text-align: right;">5.2887440</td>
<td style="text-align: right;">0.0626995</td>
<td style="text-align: right;">0.0098068</td>
</tr>
<tr class="odd">
<td style="text-align: left;">EmploymentDuration.4.to.7</td>
<td style="text-align: right;">5.2262311</td>
<td style="text-align: right;">0.0619584</td>
<td style="text-align: right;">0.0096909</td>
</tr>
<tr class="even">
<td style="text-align: left;">Telephone</td>
<td style="text-align: right;">5.1227264</td>
<td style="text-align: right;">0.0607313</td>
<td style="text-align: right;">0.0094990</td>
</tr>
<tr class="odd">
<td style="text-align: left;">Property.Unknown</td>
<td style="text-align: right;">4.8568892</td>
<td style="text-align: right;">0.0575798</td>
<td style="text-align: right;">0.0090061</td>
</tr>
<tr class="even">
<td style="text-align: left;">Housing.Rent</td>
<td style="text-align: right;">4.7812662</td>
<td style="text-align: right;">0.0566832</td>
<td style="text-align: right;">0.0088658</td>
</tr>
<tr class="odd">
<td style="text-align: left;">CreditHistory.Delay</td>
<td style="text-align: right;">4.5384483</td>
<td style="text-align: right;">0.0538046</td>
<td style="text-align: right;">0.0084156</td>
</tr>
<tr class="even">
<td style="text-align: left;">SavingsAccountBonds.Unknown</td>
<td style="text-align: right;">3.7545331</td>
<td style="text-align: right;">0.0445110</td>
<td style="text-align: right;">0.0069620</td>
</tr>
<tr class="odd">
<td style="text-align: left;">EmploymentDuration.1.to.4</td>
<td style="text-align: right;">3.6860566</td>
<td style="text-align: right;">0.0436992</td>
<td style="text-align: right;">0.0068350</td>
</tr>
<tr class="even">
<td style="text-align: left;">Job.Management.SelfEmp.HighlyQualified</td>
<td style="text-align: right;">3.5472615</td>
<td style="text-align: right;">0.0420538</td>
<td style="text-align: right;">0.0065776</td>
</tr>
<tr class="odd">
<td style="text-align: left;">Purpose.Education</td>
<td style="text-align: right;">3.3089063</td>
<td style="text-align: right;">0.0392280</td>
<td style="text-align: right;">0.0061357</td>
</tr>
<tr class="even">
<td style="text-align: left;">EmploymentDuration.gt.7</td>
<td style="text-align: right;">3.2702508</td>
<td style="text-align: right;">0.0387697</td>
<td style="text-align: right;">0.0060640</td>
</tr>
<tr class="odd">
<td style="text-align: left;">Housing.Own</td>
<td style="text-align: right;">3.0387659</td>
<td style="text-align: right;">0.0360254</td>
<td style="text-align: right;">0.0056347</td>
</tr>
<tr class="even">
<td style="text-align: left;">CreditHistory.PaidDuly</td>
<td style="text-align: right;">2.8158870</td>
<td style="text-align: right;">0.0333831</td>
<td style="text-align: right;">0.0052215</td>
</tr>
<tr class="odd">
<td style="text-align: left;">OtherDebtorsGuarantors.CoApplicant</td>
<td style="text-align: right;">2.5130854</td>
<td style="text-align: right;">0.0297933</td>
<td style="text-align: right;">0.0046600</td>
</tr>
<tr class="even">
<td style="text-align: left;">NumberPeopleMaintenance</td>
<td style="text-align: right;">2.4034374</td>
<td style="text-align: right;">0.0284934</td>
<td style="text-align: right;">0.0044567</td>
</tr>
<tr class="odd">
<td style="text-align: left;">CreditHistory.ThisBank.AllPaid</td>
<td style="text-align: right;">2.3900807</td>
<td style="text-align: right;">0.0283351</td>
<td style="text-align: right;">0.0044319</td>
</tr>
<tr class="even">
<td style="text-align: left;">CheckingAccountStatus.0.to.200</td>
<td style="text-align: right;">2.0607431</td>
<td style="text-align: right;">0.0244307</td>
<td style="text-align: right;">0.0038212</td>
</tr>
<tr class="odd">
<td style="text-align: left;">Purpose.Radio.Television</td>
<td style="text-align: right;">2.0184691</td>
<td style="text-align: right;">0.0239295</td>
<td style="text-align: right;">0.0037428</td>
</tr>
<tr class="even">
<td style="text-align: left;">Property.CarOther</td>
<td style="text-align: right;">1.9168139</td>
<td style="text-align: right;">0.0227244</td>
<td style="text-align: right;">0.0035543</td>
</tr>
<tr class="odd">
<td style="text-align: left;">Purpose.Furniture.Equipment</td>
<td style="text-align: right;">1.8031244</td>
<td style="text-align: right;">0.0213765</td>
<td style="text-align: right;">0.0033435</td>
</tr>
<tr class="even">
<td style="text-align: left;">Purpose.Business</td>
<td style="text-align: right;">1.5692081</td>
<td style="text-align: right;">0.0186034</td>
<td style="text-align: right;">0.0029098</td>
</tr>
<tr class="odd">
<td style="text-align: left;">SavingsAccountBonds.gt.1000</td>
<td style="text-align: right;">1.4338670</td>
<td style="text-align: right;">0.0169989</td>
<td style="text-align: right;">0.0026588</td>
</tr>
<tr class="even">
<td style="text-align: left;">EmploymentDuration.Unemployed</td>
<td style="text-align: right;">1.3670616</td>
<td style="text-align: right;">0.0162069</td>
<td style="text-align: right;">0.0025349</td>
</tr>
<tr class="odd">
<td style="text-align: left;">Purpose.Repairs</td>
<td style="text-align: right;">1.2434046</td>
<td style="text-align: right;">0.0147409</td>
<td style="text-align: right;">0.0023056</td>
</tr>
<tr class="even">
<td style="text-align: left;">SavingsAccountBonds.100.to.500</td>
<td style="text-align: right;">1.1172017</td>
<td style="text-align: right;">0.0132447</td>
<td style="text-align: right;">0.0020716</td>
</tr>
<tr class="odd">
<td style="text-align: left;">OtherInstallmentPlans.Stores</td>
<td style="text-align: right;">1.0155718</td>
<td style="text-align: right;">0.0120399</td>
<td style="text-align: right;">0.0018832</td>
</tr>
<tr class="even">
<td style="text-align: left;">SavingsAccountBonds.500.to.1000</td>
<td style="text-align: right;">0.7910167</td>
<td style="text-align: right;">0.0093777</td>
<td style="text-align: right;">0.0014668</td>
</tr>
<tr class="odd">
<td style="text-align: left;">ForeignWorker</td>
<td style="text-align: right;">0.5909842</td>
<td style="text-align: right;">0.0070063</td>
<td style="text-align: right;">0.0010959</td>
</tr>
<tr class="even">
<td style="text-align: left;">Job.UnskilledResident</td>
<td style="text-align: right;">0.3838074</td>
<td style="text-align: right;">0.0045501</td>
<td style="text-align: right;">0.0007117</td>
</tr>
<tr class="odd">
<td style="text-align: left;">Personal.Male.Married.Widowed</td>
<td style="text-align: right;">0.2746936</td>
<td style="text-align: right;">0.0032566</td>
<td style="text-align: right;">0.0005094</td>
</tr>
<tr class="even">
<td style="text-align: left;">Housing.ForFree</td>
<td style="text-align: right;">0.1321795</td>
<td style="text-align: right;">0.0015670</td>
<td style="text-align: right;">0.0002451</td>
</tr>
<tr class="odd">
<td style="text-align: left;">Purpose.DomesticAppliance</td>
<td style="text-align: right;">0.0000000</td>
<td style="text-align: right;">0.0000000</td>
<td style="text-align: right;">0.0000000</td>
</tr>
<tr class="even">
<td style="text-align: left;">Purpose.Retraining</td>
<td style="text-align: right;">0.0000000</td>
<td style="text-align: right;">0.0000000</td>
<td style="text-align: right;">0.0000000</td>
</tr>
<tr class="odd">
<td style="text-align: left;">Purpose.Other</td>
<td style="text-align: right;">0.0000000</td>
<td style="text-align: right;">0.0000000</td>
<td style="text-align: right;">0.0000000</td>
</tr>
<tr class="even">
<td style="text-align: left;">Personal.Male.Divorced.Seperated</td>
<td style="text-align: right;">0.0000000</td>
<td style="text-align: right;">0.0000000</td>
<td style="text-align: right;">0.0000000</td>
</tr>
<tr class="odd">
<td style="text-align: left;">Job.UnemployedUnskilled</td>
<td style="text-align: right;">0.0000000</td>
<td style="text-align: right;">0.0000000</td>
<td style="text-align: right;">0.0000000</td>
</tr>
</tbody>
</table>
</div>
</div>
</section>
<section id="dự-báo-trên-tập-test" class="level3" data-number="25.3.7">
<h3 data-number="25.3.7" class="anchored" data-anchor-id="dự-báo-trên-tập-test"><span class="header-section-number">25.3.7</span> Dự báo trên tập test</h3>
<div class="cell">
<div class="sourceCode cell-code" id="cb28"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb28-1"><a href="#cb28-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Bước 7: Dự báo trên tập test</span></span>
<span id="cb28-2"><a href="#cb28-2" aria-hidden="true" tabindex="-1"></a>pred_test1 <span class="ot">&lt;-</span> <span class="fu">h2o.predict</span>(gbm_model1, <span class="at">newdata =</span> test) <span class="sc">%&gt;%</span> </span>
<span id="cb28-3"><a href="#cb28-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">as.data.frame</span>()</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>
  |                                                                            
  |                                                                      |   0%
  |                                                                            
  |======================================================================| 100%</code></pre>
</div>
<div class="sourceCode cell-code" id="cb30"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb30-1"><a href="#cb30-1" aria-hidden="true" tabindex="-1"></a>pred_test1 <span class="sc">%&gt;%</span> head</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>  predict        Bad      Good
1     Bad 0.71166405 0.2883359
2     Bad 0.82454629 0.1754537
3     Bad 0.49154935 0.5084507
4     Bad 0.79388195 0.2061180
5    Good 0.03446872 0.9655313
6     Bad 0.76942563 0.2305744</code></pre>
</div>
</div>
<p>Nhìn vào kết quả trên, ta có thể biết được những thông tin sau:</p>
<ul>
<li>Cột <code>predict</code>: Là <code>Class</code> của khoản vay được dự báo
<ul>
<li>Good: Khoản vay không phải là khoản nợ xấu</li>
<li>Bad: Khoản vay là khoản nợ xấu</li>
</ul></li>
<li><code>Bad</code>: Xác suất khoản vay là khoản nợ xấu</li>
<li><code>Good</code>: Xác suất khoản vay là khoản không có nợ xấu</li>
</ul>
</section>
<section id="đánh-giá-chất-lượng-dự-báo-trên-test" class="level3" data-number="25.3.8">
<h3 data-number="25.3.8" class="anchored" data-anchor-id="đánh-giá-chất-lượng-dự-báo-trên-test"><span class="header-section-number">25.3.8</span> Đánh giá chất lượng dự báo trên test</h3>
<div class="cell">
<div class="sourceCode cell-code" id="cb32"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb32-1"><a href="#cb32-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Bước 8: Đánh giá chất lượng dự báo trên test</span></span>
<span id="cb32-2"><a href="#cb32-2" aria-hidden="true" tabindex="-1"></a><span class="co"># Confusion matrix</span></span>
<span id="cb32-3"><a href="#cb32-3" aria-hidden="true" tabindex="-1"></a><span class="fu">table</span>(<span class="fu">as.vector</span>(pred_test1<span class="sc">$</span>predict), </span>
<span id="cb32-4"><a href="#cb32-4" aria-hidden="true" tabindex="-1"></a>      test_df<span class="sc">$</span>Class,</span>
<span id="cb32-5"><a href="#cb32-5" aria-hidden="true" tabindex="-1"></a>      <span class="at">dnn =</span> <span class="fu">c</span>(<span class="st">"Predicted"</span>, <span class="st">"Actual"</span>)</span>
<span id="cb32-6"><a href="#cb32-6" aria-hidden="true" tabindex="-1"></a>      )</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>         Actual
Predicted Bad Good
     Bad   40   30
     Good  25  119</code></pre>
</div>
</div>
<p><strong>Note</strong>: Với H2O, chúng ta hoàn toàn có thể xây dựng mô hình trên tập train, rồi sau đó đánh giá chất lượng trên tập train và test đồng thời bằng một câu lệnh sau:</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb34"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb34-1"><a href="#cb34-1" aria-hidden="true" tabindex="-1"></a><span class="fu">set.seed</span>(<span class="dv">2</span>)</span>
<span id="cb34-2"><a href="#cb34-2" aria-hidden="true" tabindex="-1"></a>gbm_model2 <span class="ot">&lt;-</span> <span class="fu">h2o.gbm</span>(<span class="at">training_frame =</span> train, <span class="co"># Xây dựng trên train</span></span>
<span id="cb34-3"><a href="#cb34-3" aria-hidden="true" tabindex="-1"></a>                      <span class="at">x =</span> <span class="fu">setdiff</span>(<span class="fu">names</span>(GermanCredit), <span class="st">"Class"</span>),  <span class="co"># Các biến đầu vào</span></span>
<span id="cb34-4"><a href="#cb34-4" aria-hidden="true" tabindex="-1"></a>                      <span class="at">y =</span> <span class="st">"Class"</span>, <span class="co"># Biến đầu ra (biến muốn dự báo)</span></span>
<span id="cb34-5"><a href="#cb34-5" aria-hidden="true" tabindex="-1"></a>                      <span class="at">validation_frame =</span> test <span class="co"># Đánh giá trên test</span></span>
<span id="cb34-6"><a href="#cb34-6" aria-hidden="true" tabindex="-1"></a>                      )</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>
  |                                                                            
  |                                                                      |   0%
  |                                                                            
  |==================================================================    |  94%
  |                                                                            
  |======================================================================| 100%</code></pre>
</div>
<div class="sourceCode cell-code" id="cb36"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb36-1"><a href="#cb36-1" aria-hidden="true" tabindex="-1"></a>gbm_model2 <span class="sc">%&gt;%</span> summary</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>Model Details:
==============

H2OBinomialModel: gbm
Model Key:  GBM_model_R_1706352094610_5845 
Model Summary: 
  number_of_trees number_of_internal_trees model_size_in_bytes min_depth
1              50                       50               13978         5
  max_depth mean_depth min_leaves max_leaves mean_leaves
1         5    5.00000          9         26    17.58000

H2OBinomialMetrics: gbm
** Reported on training data. **

MSE:  0.07258735
RMSE:  0.2694204
LogLoss:  0.2676266
Mean Per-Class Error:  0.07134031
AUC:  0.9794455
AUCPR:  0.990769
Gini:  0.958891
R^2:  0.6536728

Confusion Matrix (vertical: actual; across: predicted) for F1-optimal threshold:
       Bad Good    Error     Rate
Bad    210   25 0.106383  =25/235
Good    20  531 0.036298  =20/551
Totals 230  556 0.057252  =45/786

Maximum Metrics: Maximum metrics at their respective thresholds
                        metric threshold      value idx
1                       max f1  0.585928   0.959350 231
2                       max f2  0.528659   0.973467 251
3                 max f0point5  0.641146   0.964326 215
4                 max accuracy  0.585928   0.942748 231
5                max precision  0.985738   1.000000   0
6                   max recall  0.301839   1.000000 324
7              max specificity  0.985738   1.000000   0
8             max absolute_mcc  0.585928   0.862683 231
9   max min_per_class_accuracy  0.650274   0.932849 211
10 max mean_per_class_accuracy  0.641146   0.936919 215
11                     max tns  0.985738 235.000000   0
12                     max fns  0.985738 550.000000   0
13                     max fps  0.050169 235.000000 399
14                     max tps  0.301839 551.000000 324
15                     max tnr  0.985738   1.000000   0
16                     max fnr  0.985738   0.998185   0
17                     max fpr  0.050169   1.000000 399
18                     max tpr  0.301839   1.000000 324

Gains/Lift Table: Extract with `h2o.gainsLift(&lt;model&gt;, &lt;data&gt;)` or `h2o.gainsLift(&lt;model&gt;, valid=&lt;T/F&gt;, xval=&lt;T/F&gt;)`
H2OBinomialMetrics: gbm
** Reported on validation data. **

MSE:  0.1745567
RMSE:  0.4177998
LogLoss:  0.5180404
Mean Per-Class Error:  0.4451729
AUC:  0.7696438
AUCPR:  0.8859651
Gini:  0.5392876
R^2:  0.1746002

Confusion Matrix (vertical: actual; across: predicted) for F1-optimal threshold:
       Bad Good    Error     Rate
Bad      8   57 0.876923   =57/65
Good     2  147 0.013423   =2/149
Totals  10  204 0.275701  =59/214

Maximum Metrics: Maximum metrics at their respective thresholds
                        metric threshold      value idx
1                       max f1  0.230574   0.832861 203
2                       max f2  0.175454   0.924318 209
3                 max f0point5  0.643835   0.829662 132
4                 max accuracy  0.579584   0.757009 148
5                max precision  0.983556   1.000000   0
6                   max recall  0.175454   1.000000 209
7              max specificity  0.983556   1.000000   0
8             max absolute_mcc  0.643835   0.427333 132
9   max min_per_class_accuracy  0.705292   0.707692 124
10 max mean_per_class_accuracy  0.643835   0.725348 132
11                     max tns  0.983556  65.000000   0
12                     max fns  0.983556 148.000000   0
13                     max fps  0.082487  65.000000 213
14                     max tps  0.175454 149.000000 209
15                     max tnr  0.983556   1.000000   0
16                     max fnr  0.983556   0.993289   0
17                     max fpr  0.082487   1.000000 213
18                     max tpr  0.175454   1.000000 209

Gains/Lift Table: Extract with `h2o.gainsLift(&lt;model&gt;, &lt;data&gt;)` or `h2o.gainsLift(&lt;model&gt;, valid=&lt;T/F&gt;, xval=&lt;T/F&gt;)`


Scoring History: 
            timestamp   duration number_of_trees training_rmse training_logloss
1 2024-01-27 11:03:00  0.010 sec               0       0.45781          0.61000
2 2024-01-27 11:03:00  0.047 sec               1       0.44489          0.58254
3 2024-01-27 11:03:00  0.072 sec               2       0.43324          0.55877
4 2024-01-27 11:03:00  0.104 sec               3       0.42313          0.53861
5 2024-01-27 11:03:00  0.134 sec               4       0.41501          0.52240
  training_auc training_pr_auc training_lift training_classification_error
1      0.50000         0.70102       1.00000                       0.29898
2      0.82314         0.91958       1.42650                       0.22774
3      0.83729         0.92585       1.42650                       0.21374
4      0.85373         0.93406       1.42650                       0.20738
5      0.86354         0.93792       1.42650                       0.19338
  validation_rmse validation_logloss validation_auc validation_pr_auc
1         0.45990            0.61405        0.50000           0.69626
2         0.45392            0.60102        0.66598           0.80764
3         0.45093            0.59421        0.66004           0.80140
4         0.44796            0.58744        0.66324           0.80763
5         0.44516            0.58122        0.67491           0.81993
  validation_lift validation_classification_error
1         1.00000                         0.30374
2         1.10480                         0.30374
3         1.07718                         0.29907
4         1.07718                         0.28037
5         0.95749                         0.26636

---
             timestamp   duration number_of_trees training_rmse
46 2024-01-27 11:03:01  1.113 sec              45       0.27706
47 2024-01-27 11:03:01  1.137 sec              46       0.27555
48 2024-01-27 11:03:01  1.158 sec              47       0.27383
49 2024-01-27 11:03:01  1.183 sec              48       0.27225
50 2024-01-27 11:03:01  1.204 sec              49       0.27105
51 2024-01-27 11:03:01  1.230 sec              50       0.26942
   training_logloss training_auc training_pr_auc training_lift
46          0.27988      0.97668         0.98933       1.42650
47          0.27727      0.97715         0.98965       1.42650
48          0.27464      0.97787         0.99002       1.42650
49          0.27199      0.97879         0.99049       1.42650
50          0.27012      0.97924         0.99069       1.42650
51          0.26763      0.97945         0.99077       1.42650
   training_classification_error validation_rmse validation_logloss
46                       0.06234         0.41681            0.51647
47                       0.06107         0.41697            0.51699
48                       0.05980         0.41727            0.51749
49                       0.05980         0.41718            0.51717
50                       0.05852         0.41795            0.51830
51                       0.05725         0.41780            0.51804
   validation_auc validation_pr_auc validation_lift
46        0.76964           0.88500         1.43624
47        0.76944           0.88436         1.43624
48        0.76820           0.88405         1.43624
49        0.76923           0.88526         1.43624
50        0.76758           0.88486         1.43624
51        0.76964           0.88597         1.43624
   validation_classification_error
46                         0.28037
47                         0.28037
48                         0.28037
49                         0.27570
50                         0.27570
51                         0.27570

Variable Importances: (Extract with `h2o.varimp`) 
=================================================

Variable Importances: 
                    variable relative_importance scaled_importance percentage
1 CheckingAccountStatus.none           84.350624          1.000000   0.156410
2                     Amount           82.419136          0.977102   0.152829
3                   Duration           68.733696          0.814857   0.127452
4                        Age           31.725632          0.376116   0.058828
5             Purpose.NewCar           19.282278          0.228597   0.035755

---
                           variable relative_importance scaled_importance
54                  Housing.ForFree            0.132180          0.001567
55        Purpose.DomesticAppliance            0.000000          0.000000
56               Purpose.Retraining            0.000000          0.000000
57                    Purpose.Other            0.000000          0.000000
58 Personal.Male.Divorced.Seperated            0.000000          0.000000
59          Job.UnemployedUnskilled            0.000000          0.000000
   percentage
54   0.000245
55   0.000000
56   0.000000
57   0.000000
58   0.000000
59   0.000000</code></pre>
</div>
</div>
</section>
<section id="tuning" class="level3" data-number="25.3.9">
<h3 data-number="25.3.9" class="anchored" data-anchor-id="tuning"><span class="header-section-number">25.3.9</span> Tuning</h3>
<p><strong>Tuning</strong> là quá trình tìm kiếm tổ hợp các tham số để tối ưu hóa mô hình (chất lượng dự báo tốt nhất có thể).</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb38"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb38-1"><a href="#cb38-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Bước 9: Tuning</span></span>
<span id="cb38-2"><a href="#cb38-2" aria-hidden="true" tabindex="-1"></a><span class="co"># 9.1. Set hyper parameters</span></span>
<span id="cb38-3"><a href="#cb38-3" aria-hidden="true" tabindex="-1"></a>hyper_params <span class="ot">=</span> <span class="fu">list</span>( </span>
<span id="cb38-4"><a href="#cb38-4" aria-hidden="true" tabindex="-1"></a>  <span class="do">## restrict the search to the range of max_depth established above</span></span>
<span id="cb38-5"><a href="#cb38-5" aria-hidden="true" tabindex="-1"></a>  <span class="at">max_depth =</span> <span class="fu">c</span>(<span class="dv">5</span><span class="sc">:</span><span class="dv">9</span>),                                      </span>
<span id="cb38-6"><a href="#cb38-6" aria-hidden="true" tabindex="-1"></a>  </span>
<span id="cb38-7"><a href="#cb38-7" aria-hidden="true" tabindex="-1"></a>  <span class="do">## search a large space of row sampling rates per tree</span></span>
<span id="cb38-8"><a href="#cb38-8" aria-hidden="true" tabindex="-1"></a>  <span class="at">sample_rate =</span> <span class="fu">seq</span>(<span class="fl">0.5</span>,<span class="dv">1</span>,<span class="fl">0.05</span>),                                             </span>
<span id="cb38-9"><a href="#cb38-9" aria-hidden="true" tabindex="-1"></a>  </span>
<span id="cb38-10"><a href="#cb38-10" aria-hidden="true" tabindex="-1"></a>  <span class="do">## search a large space of column sampling rates per split</span></span>
<span id="cb38-11"><a href="#cb38-11" aria-hidden="true" tabindex="-1"></a>  <span class="at">col_sample_rate =</span> <span class="fu">seq</span>(<span class="fl">0.5</span>,<span class="dv">1</span>,<span class="fl">0.05</span>),                                  </span>
<span id="cb38-12"><a href="#cb38-12" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb38-13"><a href="#cb38-13" aria-hidden="true" tabindex="-1"></a>  <span class="do">## search a large space of the number of min rows in a terminal node</span></span>
<span id="cb38-14"><a href="#cb38-14" aria-hidden="true" tabindex="-1"></a>  <span class="at">min_rows =</span> <span class="dv">2</span><span class="sc">^</span><span class="fu">seq</span>(<span class="dv">0</span>,<span class="fu">log2</span>(<span class="fu">nrow</span>(train))<span class="sc">-</span><span class="dv">1</span>,<span class="dv">1</span>),                                 </span>
<span id="cb38-15"><a href="#cb38-15" aria-hidden="true" tabindex="-1"></a>  </span>
<span id="cb38-16"><a href="#cb38-16" aria-hidden="true" tabindex="-1"></a>  <span class="do">## search a large space of the number of bins for split-finding for continuous and integer columns</span></span>
<span id="cb38-17"><a href="#cb38-17" aria-hidden="true" tabindex="-1"></a>  <span class="at">nbins =</span> <span class="dv">2</span><span class="sc">^</span><span class="fu">seq</span>(<span class="dv">4</span>,<span class="dv">10</span>,<span class="dv">1</span>),                                                     </span>
<span id="cb38-18"><a href="#cb38-18" aria-hidden="true" tabindex="-1"></a>  </span>
<span id="cb38-19"><a href="#cb38-19" aria-hidden="true" tabindex="-1"></a>  <span class="do">## search a large space of the number of bins for split-finding for categorical columns</span></span>
<span id="cb38-20"><a href="#cb38-20" aria-hidden="true" tabindex="-1"></a>  <span class="at">nbins_cats =</span> <span class="dv">2</span><span class="sc">^</span><span class="fu">seq</span>(<span class="dv">4</span>,<span class="dv">12</span>,<span class="dv">1</span>),                                                </span>
<span id="cb38-21"><a href="#cb38-21" aria-hidden="true" tabindex="-1"></a>  </span>
<span id="cb38-22"><a href="#cb38-22" aria-hidden="true" tabindex="-1"></a>  <span class="do">## search a few minimum required relative error improvement thresholds for a split to happen</span></span>
<span id="cb38-23"><a href="#cb38-23" aria-hidden="true" tabindex="-1"></a>  <span class="at">min_split_improvement =</span> <span class="fu">c</span>(<span class="dv">0</span>,<span class="fl">1e-8</span>,<span class="fl">1e-6</span>,<span class="fl">1e-4</span>),                               </span>
<span id="cb38-24"><a href="#cb38-24" aria-hidden="true" tabindex="-1"></a>  </span>
<span id="cb38-25"><a href="#cb38-25" aria-hidden="true" tabindex="-1"></a>  <span class="do">## try all histogram types (QuantilesGlobal and RoundRobin are good for numeric columns with outliers)</span></span>
<span id="cb38-26"><a href="#cb38-26" aria-hidden="true" tabindex="-1"></a>  <span class="at">histogram_type =</span> <span class="fu">c</span>(<span class="st">"UniformAdaptive"</span>,<span class="st">"QuantilesGlobal"</span>,<span class="st">"RoundRobin"</span>)      </span>
<span id="cb38-27"><a href="#cb38-27" aria-hidden="true" tabindex="-1"></a>)</span>
<span id="cb38-28"><a href="#cb38-28" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb38-29"><a href="#cb38-29" aria-hidden="true" tabindex="-1"></a><span class="co"># 9.2. Set search criteria</span></span>
<span id="cb38-30"><a href="#cb38-30" aria-hidden="true" tabindex="-1"></a>search_criteria <span class="ot">=</span> <span class="fu">list</span>(</span>
<span id="cb38-31"><a href="#cb38-31" aria-hidden="true" tabindex="-1"></a>  <span class="do">## Random grid search</span></span>
<span id="cb38-32"><a href="#cb38-32" aria-hidden="true" tabindex="-1"></a>  <span class="at">strategy =</span> <span class="st">"RandomDiscrete"</span>,      </span>
<span id="cb38-33"><a href="#cb38-33" aria-hidden="true" tabindex="-1"></a>  </span>
<span id="cb38-34"><a href="#cb38-34" aria-hidden="true" tabindex="-1"></a>  <span class="do">## limit the runtime to xx minutes</span></span>
<span id="cb38-35"><a href="#cb38-35" aria-hidden="true" tabindex="-1"></a>  <span class="at">max_runtime_secs =</span> <span class="dv">10</span>,         </span>
<span id="cb38-36"><a href="#cb38-36" aria-hidden="true" tabindex="-1"></a>  </span>
<span id="cb38-37"><a href="#cb38-37" aria-hidden="true" tabindex="-1"></a>  <span class="do">## build no more than xx models</span></span>
<span id="cb38-38"><a href="#cb38-38" aria-hidden="true" tabindex="-1"></a>  <span class="at">max_models =</span> <span class="dv">5</span>,                  </span>
<span id="cb38-39"><a href="#cb38-39" aria-hidden="true" tabindex="-1"></a>  </span>
<span id="cb38-40"><a href="#cb38-40" aria-hidden="true" tabindex="-1"></a>  <span class="do">## random number generator seed to make sampling of parameter combinations reproducible</span></span>
<span id="cb38-41"><a href="#cb38-41" aria-hidden="true" tabindex="-1"></a>  <span class="at">seed =</span> <span class="dv">1234</span>,                        </span>
<span id="cb38-42"><a href="#cb38-42" aria-hidden="true" tabindex="-1"></a>  </span>
<span id="cb38-43"><a href="#cb38-43" aria-hidden="true" tabindex="-1"></a>  <span class="do">## early stopping once the leaderboard of the top 5 models is converged to 0.1% relative difference</span></span>
<span id="cb38-44"><a href="#cb38-44" aria-hidden="true" tabindex="-1"></a>  <span class="at">stopping_rounds =</span> <span class="dv">5</span>,                </span>
<span id="cb38-45"><a href="#cb38-45" aria-hidden="true" tabindex="-1"></a>  <span class="at">stopping_metric =</span> <span class="st">"AUC"</span>,</span>
<span id="cb38-46"><a href="#cb38-46" aria-hidden="true" tabindex="-1"></a>  <span class="at">stopping_tolerance =</span> <span class="fl">1e-3</span></span>
<span id="cb38-47"><a href="#cb38-47" aria-hidden="true" tabindex="-1"></a>)</span>
<span id="cb38-48"><a href="#cb38-48" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb38-49"><a href="#cb38-49" aria-hidden="true" tabindex="-1"></a><span class="co"># 9.3. Grid search</span></span>
<span id="cb38-50"><a href="#cb38-50" aria-hidden="true" tabindex="-1"></a>grid <span class="ot">&lt;-</span> <span class="fu">h2o.grid</span>(</span>
<span id="cb38-51"><a href="#cb38-51" aria-hidden="true" tabindex="-1"></a>  <span class="do">## hyper parameters</span></span>
<span id="cb38-52"><a href="#cb38-52" aria-hidden="true" tabindex="-1"></a>  <span class="at">hyper_params =</span> hyper_params,</span>
<span id="cb38-53"><a href="#cb38-53" aria-hidden="true" tabindex="-1"></a>  </span>
<span id="cb38-54"><a href="#cb38-54" aria-hidden="true" tabindex="-1"></a>  <span class="do">## hyper-parameter search configuration (see above)</span></span>
<span id="cb38-55"><a href="#cb38-55" aria-hidden="true" tabindex="-1"></a>  <span class="at">search_criteria =</span> search_criteria,</span>
<span id="cb38-56"><a href="#cb38-56" aria-hidden="true" tabindex="-1"></a>  </span>
<span id="cb38-57"><a href="#cb38-57" aria-hidden="true" tabindex="-1"></a>  <span class="do">## which algorithm to run</span></span>
<span id="cb38-58"><a href="#cb38-58" aria-hidden="true" tabindex="-1"></a>  <span class="at">algorithm =</span> <span class="st">"gbm"</span>,</span>
<span id="cb38-59"><a href="#cb38-59" aria-hidden="true" tabindex="-1"></a>  </span>
<span id="cb38-60"><a href="#cb38-60" aria-hidden="true" tabindex="-1"></a>  <span class="do">## identifier for the grid, to later retrieve it</span></span>
<span id="cb38-61"><a href="#cb38-61" aria-hidden="true" tabindex="-1"></a>  <span class="at">grid_id =</span> <span class="st">"model_id"</span>, </span>
<span id="cb38-62"><a href="#cb38-62" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb38-63"><a href="#cb38-63" aria-hidden="true" tabindex="-1"></a>  <span class="do">## standard model parameters</span></span>
<span id="cb38-64"><a href="#cb38-64" aria-hidden="true" tabindex="-1"></a>  <span class="at">x =</span> <span class="fu">setdiff</span>(<span class="fu">names</span>(GermanCredit), <span class="st">"Class"</span>), </span>
<span id="cb38-65"><a href="#cb38-65" aria-hidden="true" tabindex="-1"></a>  <span class="at">y =</span> <span class="st">"Class"</span>, </span>
<span id="cb38-66"><a href="#cb38-66" aria-hidden="true" tabindex="-1"></a>  <span class="at">training_frame =</span> train, </span>
<span id="cb38-67"><a href="#cb38-67" aria-hidden="true" tabindex="-1"></a>  <span class="at">validation_frame =</span> test,</span>
<span id="cb38-68"><a href="#cb38-68" aria-hidden="true" tabindex="-1"></a>  <span class="co">#balance_classes = T, #Option to solve imbalanced classification</span></span>
<span id="cb38-69"><a href="#cb38-69" aria-hidden="true" tabindex="-1"></a>  </span>
<span id="cb38-70"><a href="#cb38-70" aria-hidden="true" tabindex="-1"></a>  <span class="do">## more trees is better if the learning rate is small enough</span></span>
<span id="cb38-71"><a href="#cb38-71" aria-hidden="true" tabindex="-1"></a>  <span class="do">## use "more than enough" trees - we have early stopping</span></span>
<span id="cb38-72"><a href="#cb38-72" aria-hidden="true" tabindex="-1"></a>  <span class="at">ntrees =</span> <span class="dv">200</span>,                                                            </span>
<span id="cb38-73"><a href="#cb38-73" aria-hidden="true" tabindex="-1"></a>  </span>
<span id="cb38-74"><a href="#cb38-74" aria-hidden="true" tabindex="-1"></a>  <span class="do">## smaller learning rate is better</span></span>
<span id="cb38-75"><a href="#cb38-75" aria-hidden="true" tabindex="-1"></a>  <span class="do">## since we have learning_rate_annealing, we can afford to start with a bigger learning rate</span></span>
<span id="cb38-76"><a href="#cb38-76" aria-hidden="true" tabindex="-1"></a>  <span class="at">learn_rate =</span> <span class="fl">0.05</span>,                                                         </span>
<span id="cb38-77"><a href="#cb38-77" aria-hidden="true" tabindex="-1"></a>  </span>
<span id="cb38-78"><a href="#cb38-78" aria-hidden="true" tabindex="-1"></a>  <span class="do">## learning rate annealing: learning_rate shrinks by 1% after every tree </span></span>
<span id="cb38-79"><a href="#cb38-79" aria-hidden="true" tabindex="-1"></a>  <span class="do">## (use 1.00 to disable, but then lower the learning_rate)</span></span>
<span id="cb38-80"><a href="#cb38-80" aria-hidden="true" tabindex="-1"></a>  <span class="at">learn_rate_annealing =</span> <span class="fl">0.99</span>,                                               </span>
<span id="cb38-81"><a href="#cb38-81" aria-hidden="true" tabindex="-1"></a>  </span>
<span id="cb38-82"><a href="#cb38-82" aria-hidden="true" tabindex="-1"></a>  <span class="do">## early stopping based on timeout (no model should take more than 1 hour - modify as needed)</span></span>
<span id="cb38-83"><a href="#cb38-83" aria-hidden="true" tabindex="-1"></a>  <span class="at">max_runtime_secs =</span> <span class="dv">30</span>,                                                 </span>
<span id="cb38-84"><a href="#cb38-84" aria-hidden="true" tabindex="-1"></a>  </span>
<span id="cb38-85"><a href="#cb38-85" aria-hidden="true" tabindex="-1"></a>  <span class="do">## early stopping once the validation AUC doesn't improve by at least 0.01% for 5 consecutive scoring events</span></span>
<span id="cb38-86"><a href="#cb38-86" aria-hidden="true" tabindex="-1"></a>  <span class="at">stopping_rounds =</span> <span class="dv">5</span>, <span class="at">stopping_tolerance =</span> <span class="fl">1e-3</span>, <span class="at">stopping_metric =</span> <span class="st">"AUC"</span>, </span>
<span id="cb38-87"><a href="#cb38-87" aria-hidden="true" tabindex="-1"></a>  </span>
<span id="cb38-88"><a href="#cb38-88" aria-hidden="true" tabindex="-1"></a>  <span class="do">## score every 10 trees to make early stopping reproducible (it depends on the scoring interval)</span></span>
<span id="cb38-89"><a href="#cb38-89" aria-hidden="true" tabindex="-1"></a>  <span class="at">score_tree_interval =</span> <span class="dv">10</span>,                                                </span>
<span id="cb38-90"><a href="#cb38-90" aria-hidden="true" tabindex="-1"></a>  </span>
<span id="cb38-91"><a href="#cb38-91" aria-hidden="true" tabindex="-1"></a>  <span class="do">## base random number generator seed for each model (automatically gets incremented internally for each model)</span></span>
<span id="cb38-92"><a href="#cb38-92" aria-hidden="true" tabindex="-1"></a>  <span class="at">seed =</span> <span class="dv">1234</span>                                                             </span>
<span id="cb38-93"><a href="#cb38-93" aria-hidden="true" tabindex="-1"></a>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>
  |                                                                            
  |                                                                      |   0%
  |                                                                            
  |========                                                              |  11%
  |                                                                            
  |======================                                                |  31%
  |                                                                            
  |====================================                                  |  51%
  |                                                                            
  |==================================================                    |  71%
  |                                                                            
  |================================================================      |  91%
  |                                                                            
  |======================================================================| 100%</code></pre>
</div>
<div class="sourceCode cell-code" id="cb40"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb40-1"><a href="#cb40-1" aria-hidden="true" tabindex="-1"></a><span class="co"># 9.4. Get models</span></span>
<span id="cb40-2"><a href="#cb40-2" aria-hidden="true" tabindex="-1"></a>sortedGrid <span class="ot">&lt;-</span> <span class="fu">h2o.getGrid</span>(<span class="st">"model_id"</span>, <span class="at">sort_by =</span> <span class="st">"auc"</span>, <span class="at">decreasing =</span> <span class="cn">TRUE</span>)    </span>
<span id="cb40-3"><a href="#cb40-3" aria-hidden="true" tabindex="-1"></a>sortedGrid</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>H2O Grid Details
================

Grid ID: model_id 
Used hyper parameters: 
  -  col_sample_rate 
  -  histogram_type 
  -  max_depth 
  -  min_rows 
  -  min_split_improvement 
  -  nbins 
  -  nbins_cats 
  -  sample_rate 
Number of models: 3 
Number of failed models: 0 

Hyper-Parameter Search Summary: ordered by decreasing auc
  col_sample_rate  histogram_type max_depth min_rows min_split_improvement
1         0.80000 UniformAdaptive   7.00000  1.00000               0.00000
2         0.75000 QuantilesGlobal   5.00000 32.00000               0.00000
3         0.85000      RoundRobin   8.00000  1.00000               0.00010
      nbins nbins_cats sample_rate        model_ids     auc
1 512.00000 2048.00000     0.55000 model_id_model_3 0.77873
2  64.00000  512.00000     0.50000 model_id_model_2 0.77233
3  16.00000  256.00000     0.55000 model_id_model_1 0.76386</code></pre>
</div>
<div class="sourceCode cell-code" id="cb42"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb42-1"><a href="#cb42-1" aria-hidden="true" tabindex="-1"></a><span class="co"># 9.5. Get best model</span></span>
<span id="cb42-2"><a href="#cb42-2" aria-hidden="true" tabindex="-1"></a>gbm <span class="ot">&lt;-</span> <span class="fu">h2o.getModel</span>(sortedGrid<span class="sc">@</span>model_ids[[<span class="dv">1</span>]])</span>
<span id="cb42-3"><a href="#cb42-3" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb42-4"><a href="#cb42-4" aria-hidden="true" tabindex="-1"></a><span class="co"># Parameters of the best model</span></span>
<span id="cb42-5"><a href="#cb42-5" aria-hidden="true" tabindex="-1"></a>gbm<span class="sc">@</span>parameters</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>$model_id
[1] "model_id_model_3"

$training_frame
[1] "RTMP_sid_be09_3"

$validation_frame
[1] "RTMP_sid_be09_5"

$score_tree_interval
[1] 10

$ntrees
[1] 200

$max_depth
[1] 7

$min_rows
[1] 1

$nbins
[1] 512

$nbins_cats
[1] 2048

$stopping_rounds
[1] 5

$stopping_metric
[1] "AUC"

$max_runtime_secs
[1] 1.978

$seed
[1] 1234

$learn_rate
[1] 0.05

$learn_rate_annealing
[1] 0.99

$distribution
[1] "bernoulli"

$sample_rate
[1] 0.55

$col_sample_rate
[1] 0.8

$min_split_improvement
[1] 1e-08

$histogram_type
[1] "UniformAdaptive"

$categorical_encoding
[1] "Enum"

$calibration_method
[1] "PlattScaling"

$x
 [1] "Duration"                              
 [2] "Amount"                                
 [3] "InstallmentRatePercentage"             
 [4] "ResidenceDuration"                     
 [5] "Age"                                   
 [6] "NumberExistingCredits"                 
 [7] "NumberPeopleMaintenance"               
 [8] "Telephone"                             
 [9] "ForeignWorker"                         
[10] "CheckingAccountStatus.lt.0"            
[11] "CheckingAccountStatus.0.to.200"        
[12] "CheckingAccountStatus.gt.200"          
[13] "CheckingAccountStatus.none"            
[14] "CreditHistory.NoCredit.AllPaid"        
[15] "CreditHistory.ThisBank.AllPaid"        
[16] "CreditHistory.PaidDuly"                
[17] "CreditHistory.Delay"                   
[18] "CreditHistory.Critical"                
[19] "Purpose.NewCar"                        
[20] "Purpose.UsedCar"                       
[21] "Purpose.Furniture.Equipment"           
[22] "Purpose.Radio.Television"              
[23] "Purpose.DomesticAppliance"             
[24] "Purpose.Repairs"                       
[25] "Purpose.Education"                     
[26] "Purpose.Retraining"                    
[27] "Purpose.Business"                      
[28] "Purpose.Other"                         
[29] "SavingsAccountBonds.lt.100"            
[30] "SavingsAccountBonds.100.to.500"        
[31] "SavingsAccountBonds.500.to.1000"       
[32] "SavingsAccountBonds.gt.1000"           
[33] "SavingsAccountBonds.Unknown"           
[34] "EmploymentDuration.lt.1"               
[35] "EmploymentDuration.1.to.4"             
[36] "EmploymentDuration.4.to.7"             
[37] "EmploymentDuration.gt.7"               
[38] "EmploymentDuration.Unemployed"         
[39] "Personal.Male.Divorced.Seperated"      
[40] "Personal.Female.NotSingle"             
[41] "Personal.Male.Single"                  
[42] "Personal.Male.Married.Widowed"         
[43] "OtherDebtorsGuarantors.None"           
[44] "OtherDebtorsGuarantors.CoApplicant"    
[45] "OtherDebtorsGuarantors.Guarantor"      
[46] "Property.RealEstate"                   
[47] "Property.Insurance"                    
[48] "Property.CarOther"                     
[49] "Property.Unknown"                      
[50] "OtherInstallmentPlans.Bank"            
[51] "OtherInstallmentPlans.Stores"          
[52] "OtherInstallmentPlans.None"            
[53] "Housing.Rent"                          
[54] "Housing.Own"                           
[55] "Housing.ForFree"                       
[56] "Job.UnemployedUnskilled"               
[57] "Job.UnskilledResident"                 
[58] "Job.SkilledEmployee"                   
[59] "Job.Management.SelfEmp.HighlyQualified"

$y
[1] "Class"</code></pre>
</div>
<div class="sourceCode cell-code" id="cb44"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb44-1"><a href="#cb44-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Summary best model</span></span>
<span id="cb44-2"><a href="#cb44-2" aria-hidden="true" tabindex="-1"></a>gbm <span class="sc">%&gt;%</span> summary</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>Model Details:
==============

H2OBinomialModel: gbm
Model Key:  model_id_model_3 
Model Summary: 
  number_of_trees number_of_internal_trees model_size_in_bytes min_depth
1             160                      160              132081         7
  max_depth mean_depth min_leaves max_leaves mean_leaves
1         7    7.00000         37         90    60.88750

H2OBinomialMetrics: gbm
** Reported on training data. **

MSE:  0.0301219
RMSE:  0.1735566
LogLoss:  0.1504146
Mean Per-Class Error:  0.003942542
AUC:  0.9997027
AUCPR:  0.9998713
Gini:  0.9994053
R^2:  0.8562831

Confusion Matrix (vertical: actual; across: predicted) for F1-optimal threshold:
       Bad Good    Error    Rate
Bad    234    1 0.004255  =1/235
Good     2  549 0.003630  =2/551
Totals 236  550 0.003817  =3/786

Maximum Metrics: Maximum metrics at their respective thresholds
                        metric threshold      value idx
1                       max f1  0.584274   0.997275 221
2                       max f2  0.559127   0.997461 224
3                 max f0point5  0.584274   0.997819 221
4                 max accuracy  0.584274   0.996183 221
5                max precision  0.987277   1.000000   0
6                   max recall  0.499648   1.000000 231
7              max specificity  0.987277   1.000000   0
8             max absolute_mcc  0.584274   0.990910 221
9   max min_per_class_accuracy  0.584274   0.995745 221
10 max mean_per_class_accuracy  0.584274   0.996057 221
11                     max tns  0.987277 235.000000   0
12                     max fns  0.987277 550.000000   0
13                     max fps  0.049099 235.000000 399
14                     max tps  0.499648 551.000000 231
15                     max tnr  0.987277   1.000000   0
16                     max fnr  0.987277   0.998185   0
17                     max fpr  0.049099   1.000000 399
18                     max tpr  0.499648   1.000000 231

Gains/Lift Table: Extract with `h2o.gainsLift(&lt;model&gt;, &lt;data&gt;)` or `h2o.gainsLift(&lt;model&gt;, valid=&lt;T/F&gt;, xval=&lt;T/F&gt;)`
H2OBinomialMetrics: gbm
** Reported on validation data. **

MSE:  0.1698508
RMSE:  0.4121295
LogLoss:  0.5118234
Mean Per-Class Error:  0.411048
AUC:  0.77873
AUCPR:  0.886226
Gini:  0.55746
R^2:  0.1968523

Confusion Matrix (vertical: actual; across: predicted) for F1-optimal threshold:
       Bad Good    Error     Rate
Bad     12   53 0.815385   =53/65
Good     1  148 0.006711   =1/149
Totals  13  201 0.252336  =54/214

Maximum Metrics: Maximum metrics at their respective thresholds
                        metric threshold      value idx
1                       max f1  0.270659   0.845714 200
2                       max f2  0.270659   0.928482 200
3                 max f0point5  0.609504   0.821095 149
4                 max accuracy  0.568169   0.757009 158
5                max precision  0.984562   1.000000   0
6                   max recall  0.146165   1.000000 210
7              max specificity  0.984562   1.000000   0
8             max absolute_mcc  0.609504   0.411930 149
9   max min_per_class_accuracy  0.734044   0.707692 124
10 max mean_per_class_accuracy  0.748205   0.715849 116
11                     max tns  0.984562  65.000000   0
12                     max fns  0.984562 148.000000   0
13                     max fps  0.092630  65.000000 213
14                     max tps  0.146165 149.000000 210
15                     max tnr  0.984562   1.000000   0
16                     max fnr  0.984562   0.993289   0
17                     max fpr  0.092630   1.000000 213
18                     max tpr  0.146165   1.000000 210

Gains/Lift Table: Extract with `h2o.gainsLift(&lt;model&gt;, &lt;data&gt;)` or `h2o.gainsLift(&lt;model&gt;, valid=&lt;T/F&gt;, xval=&lt;T/F&gt;)`


Scoring History: 
             timestamp   duration number_of_trees training_rmse
1  2024-01-27 11:03:10  8.035 sec               0       0.45781
2  2024-01-27 11:03:11  8.230 sec              10       0.38021
3  2024-01-27 11:03:11  8.379 sec              20       0.33012
4  2024-01-27 11:03:11  8.502 sec              30       0.29559
5  2024-01-27 11:03:11  8.604 sec              40       0.27103
6  2024-01-27 11:03:11  8.705 sec              50       0.25164
7  2024-01-27 11:03:11  8.810 sec              60       0.23528
8  2024-01-27 11:03:11  8.914 sec              70       0.22403
9  2024-01-27 11:03:11  9.013 sec              80       0.21344
10 2024-01-27 11:03:11  9.125 sec              90       0.20578
11 2024-01-27 11:03:12  9.233 sec             100       0.19796
12 2024-01-27 11:03:12  9.357 sec             110       0.19256
13 2024-01-27 11:03:12  9.499 sec             120       0.18836
14 2024-01-27 11:03:12  9.631 sec             130       0.18327
15 2024-01-27 11:03:12  9.729 sec             140       0.17954
16 2024-01-27 11:03:12  9.872 sec             150       0.17647
17 2024-01-27 11:03:12 10.019 sec             160       0.17356
   training_logloss training_auc training_pr_auc training_lift
1           0.61000      0.50000         0.70102       1.00000
2           0.45947      0.96683         0.98507       1.42650
3           0.37361      0.98343         0.99259       1.42650
4           0.31846      0.99070         0.99579       1.42650
5           0.28075      0.99421         0.99734       1.42650
6           0.25232      0.99597         0.99820       1.42650
7           0.22911      0.99682         0.99859       1.42650
8           0.21353      0.99772         0.99901       1.42650
9           0.19968      0.99841         0.99931       1.42650
10          0.18953      0.99878         0.99947       1.42650
11          0.17986      0.99908         0.99961       1.42650
12          0.17317      0.99919         0.99965       1.42650
13          0.16761      0.99928         0.99969       1.42650
14          0.16165      0.99944         0.99976       1.42650
15          0.15721      0.99957         0.99981       1.42650
16          0.15372      0.99963         0.99984       1.42650
17          0.15041      0.99970         0.99987       1.42650
   training_classification_error validation_rmse validation_logloss
1                        0.29898         0.45990            0.61405
2                        0.08524         0.43380            0.55706
3                        0.06107         0.42038            0.52747
4                        0.04453         0.41787            0.52099
5                        0.03181         0.41491            0.51435
6                        0.02417         0.41453            0.51243
7                        0.02163         0.41477            0.51231
8                        0.01908         0.41367            0.51055
9                        0.01527         0.41347            0.51122
10                       0.01527         0.41203            0.50889
11                       0.01145         0.41213            0.50923
12                       0.01018         0.41182            0.50903
13                       0.00891         0.41179            0.50945
14                       0.00763         0.41150            0.50925
15                       0.00763         0.41181            0.51021
16                       0.00636         0.41169            0.51012
17                       0.00382         0.41213            0.51182
   validation_auc validation_pr_auc validation_lift
1         0.50000           0.69626         1.00000
2         0.74734           0.88451         1.43624
3         0.76851           0.88894         1.43624
4         0.76489           0.88515         1.43624
5         0.77078           0.88528         1.43624
6         0.77202           0.88675         1.43624
7         0.77481           0.88866         1.43624
8         0.77584           0.88846         1.43624
9         0.77739           0.88715         1.43624
10        0.77904           0.88849         1.43624
11        0.77801           0.88722         1.43624
12        0.78007           0.88798         1.43624
13        0.78152           0.88848         1.43624
14        0.78286           0.88893         1.43624
15        0.78080           0.88712         1.43624
16        0.78090           0.88723         1.43624
17        0.77873           0.88623         1.43624
   validation_classification_error
1                          0.30374
2                          0.28972
3                          0.27103
4                          0.26636
5                          0.25234
6                          0.25234
7                          0.25701
8                          0.27570
9                          0.26636
10                         0.26168
11                         0.25701
12                         0.25701
13                         0.26168
14                         0.25701
15                         0.25701
16                         0.25234
17                         0.25234

Variable Importances: (Extract with `h2o.varimp`) 
=================================================

Variable Importances: 
                    variable relative_importance scaled_importance percentage
1                     Amount          313.728577          1.000000   0.157860
2                        Age          189.207153          0.603092   0.095204
3                   Duration          183.591110          0.585191   0.092379
4 CheckingAccountStatus.none          182.698227          0.582345   0.091929
5          ResidenceDuration           73.159607          0.233194   0.036812

---
                    variable relative_importance scaled_importance percentage
54           Purpose.Repairs            8.041581          0.025632   0.004046
55 Purpose.DomesticAppliance            6.466620          0.020612   0.003254
56   Job.UnemployedUnskilled            6.073302          0.019358   0.003056
57             ForeignWorker            5.531750          0.017632   0.002783
58        Purpose.Retraining            2.407418          0.007674   0.001211
59             Purpose.Other            1.443236          0.004600   0.000726</code></pre>
</div>
</div>
</section>
<section id="lưu-và-load-mô-hình" class="level3" data-number="25.3.10">
<h3 data-number="25.3.10" class="anchored" data-anchor-id="lưu-và-load-mô-hình"><span class="header-section-number">25.3.10</span> Lưu và load mô hình</h3>
<p>Để lưu lại mô hình trên H2O, chúng ta sử dụng câu lệnh <code>h2o.saveModel()</code>.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb46"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb46-1"><a href="#cb46-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Lưu model</span></span>
<span id="cb46-2"><a href="#cb46-2" aria-hidden="true" tabindex="-1"></a><span class="fu">h2o.saveModel</span>(gbm, <span class="co"># Tên mô hình</span></span>
<span id="cb46-3"><a href="#cb46-3" aria-hidden="true" tabindex="-1"></a>              <span class="at">path =</span> <span class="fu">getwd</span>(), <span class="co"># Đường dẫn muốn lưu</span></span>
<span id="cb46-4"><a href="#cb46-4" aria-hidden="true" tabindex="-1"></a>              <span class="at">force =</span> T)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<p>Để load mô hình trên H2O, chúng ta sử dụng câu lệnh <code>h2o.loadModel()</code>.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb47"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb47-1"><a href="#cb47-1" aria-hidden="true" tabindex="-1"></a><span class="fu">h2o.shutdown</span>(<span class="at">prompt =</span> F)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<center>
<font size="4">§</font>
</center>
<p>Như vậy, trong chương này, chúng ta được học cách xây dựng mô hình dự báo với H2O. Đây là một platform rất mạnh giúp cải thiện chất lượng dự báo, tốc độ xử lý, tối ưu hóa mô hình, cũng như hiển thị kết quả mô hình một cách rất hiệu quả.</p>
</section>
</section>
<section id="tìm-kiếm-mô-hình-tự-động" class="level2" data-number="25.4">
<h2 data-number="25.4" class="anchored" data-anchor-id="tìm-kiếm-mô-hình-tự-động"><span class="header-section-number">25.4</span> Tìm kiếm mô hình tự động</h2>
<p>Bên cạnh các mô hình thông thường như random forest, gbm,… <code>h2o</code> còn cho phép tự động xây dựng mô hình với hàm <code>h2o.automl</code> bằng cách xây dựng 1 loạt nhiều mô hình về đánh giá hiệu quả mô hình. Bên cạnh các thuật toán thông thường, h2o còn có thể sử dụng cả các thuật toán thuộc nhóm <code>stack ensemble</code> khi kết hợp kết quả đầu ra của nhiều mô hình</p>
<p>Xêm thêm hướng dẫn về <a href="https://docs.h2o.ai/h2o/latest-stable/h2o-docs/automl.html">h2o.automl</a></p>
<div class="cell">
<div class="sourceCode cell-code" id="cb48"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb48-1"><a href="#cb48-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Bước 6: Xây dựng mô hình trên train</span></span>
<span id="cb48-2"><a href="#cb48-2" aria-hidden="true" tabindex="-1"></a><span class="fu">set.seed</span>(<span class="dv">1</span>)</span>
<span id="cb48-3"><a href="#cb48-3" aria-hidden="true" tabindex="-1"></a>auto_model <span class="ot">&lt;-</span> <span class="fu">h2o.automl</span>(<span class="at">training_frame =</span> train, <span class="co"># Tập dữ liệu train</span></span>
<span id="cb48-4"><a href="#cb48-4" aria-hidden="true" tabindex="-1"></a>                      <span class="at">x =</span> <span class="fu">setdiff</span>(<span class="fu">names</span>(GermanCredit), <span class="st">"Class"</span>),  <span class="co"># Các biến đầu vào</span></span>
<span id="cb48-5"><a href="#cb48-5" aria-hidden="true" tabindex="-1"></a>                      <span class="at">y =</span> <span class="st">"Class"</span>, <span class="co"># Biến đầu ra (biến muốn dự báo),</span></span>
<span id="cb48-6"><a href="#cb48-6" aria-hidden="true" tabindex="-1"></a>                      <span class="at">max_runtime_secs =</span> <span class="dv">60</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>
  |                                                                            
  |                                                                      |   0%
  |                                                                            
  |=                                                                     |   2%
11:03:13.755: _train param, Dropping bad and constant columns: [Personal.Female.Single, Purpose.Vacation]
  |                                                                            
  |====                                                                  |   5%
11:03:16.671: _train param, Dropping bad and constant columns: [Personal.Female.Single, Purpose.Vacation]
  |                                                                            
  |======                                                                |   9%
11:03:18.826: _train param, Dropping bad and constant columns: [Personal.Female.Single, Purpose.Vacation]
  |                                                                            
  |========                                                              |  12%
11:03:21.146: _train param, Dropping unused columns: [Personal.Female.Single, Purpose.Vacation]
11:03:21.511: _train param, Dropping bad and constant columns: [Personal.Female.Single, Purpose.Vacation]
  |                                                                            
  |===========                                                           |  16%
11:03:24.139: _train param, Dropping bad and constant columns: [Personal.Female.Single, Purpose.Vacation]
  |                                                                            
  |=============                                                         |  19%
  |                                                                            
  |================                                                      |  23%
  |                                                                            
  |==================                                                    |  26%
11:03:28.822: _train param, Dropping bad and constant columns: [Personal.Female.Single, Purpose.Vacation]
  |                                                                            
  |=====================                                                 |  29%
11:03:30.987: _train param, Dropping bad and constant columns: [Personal.Female.Single, Purpose.Vacation]
  |                                                                            
  |=======================                                               |  33%
11:03:33.342: _train param, Dropping bad and constant columns: [Personal.Female.Single, Purpose.Vacation]
  |                                                                            
  |=========================                                             |  36%
11:03:36.296: _train param, Dropping unused columns: [Personal.Female.Single, Purpose.Vacation]
  |                                                                            
  |============================                                          |  40%
11:03:36.778: _train param, Dropping unused columns: [Personal.Female.Single, Purpose.Vacation]
11:03:37.280: _train param, Dropping bad and constant columns: [Personal.Female.Single, Purpose.Vacation]
  |                                                                            
  |==============================                                        |  43%
11:03:39.961: _train param, Dropping bad and constant columns: [Personal.Female.Single, Purpose.Vacation]
  |                                                                            
  |=================================                                     |  47%
11:03:41.611: _train param, Dropping bad and constant columns: [Personal.Female.Single, Purpose.Vacation]
  |                                                                            
  |===================================                                   |  50%
11:03:43.627: _train param, Dropping bad and constant columns: [Personal.Female.Single, Purpose.Vacation]
  |                                                                            
  |======================================                                |  54%
11:03:45.449: _train param, Dropping unused columns: [Personal.Female.Single, Purpose.Vacation]
11:03:45.955: _train param, Dropping unused columns: [Personal.Female.Single, Purpose.Vacation]
  |                                                                            
  |========================================                              |  57%
  |                                                                            
  |===========================================                           |  61%
  |                                                                            
  |=============================================                         |  64%
  |                                                                            
  |===============================================                       |  68%
  |                                                                            
  |==================================================                    |  71%
  |                                                                            
  |====================================================                  |  75%
  |                                                                            
  |=======================================================               |  78%
  |                                                                            
  |=========================================================             |  82%
  |                                                                            
  |============================================================          |  85%
  |                                                                            
  |==============================================================        |  89%
  |                                                                            
  |=================================================================     |  92%
  |                                                                            
  |===================================================================   |  96%
11:04:12.107: _train param, Dropping unused columns: [Personal.Female.Single, Purpose.Vacation]
  |                                                                            
  |======================================================================|  99%
11:04:12.504: _train param, Dropping unused columns: [Personal.Female.Single, Purpose.Vacation]
  |                                                                            
  |======================================================================| 100%</code></pre>
</div>
<div class="sourceCode cell-code" id="cb50"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb50-1"><a href="#cb50-1" aria-hidden="true" tabindex="-1"></a>leader_board <span class="ot">&lt;-</span> auto_model<span class="sc">@</span>leaderboard</span>
<span id="cb50-2"><a href="#cb50-2" aria-hidden="true" tabindex="-1"></a><span class="fu">print</span>(leader_board)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>                                                 model_id       auc   logloss
1 StackedEnsemble_BestOfFamily_4_AutoML_3_20240127_110313 0.7925860 0.4898369
2 StackedEnsemble_BestOfFamily_1_AutoML_3_20240127_110313 0.7888404 0.4944783
3 StackedEnsemble_BestOfFamily_3_AutoML_3_20240127_110313 0.7885006 0.4937585
4                          GLM_1_AutoML_3_20240127_110313 0.7879137 0.4948324
5    StackedEnsemble_AllModels_1_AutoML_3_20240127_110313 0.7851489 0.4962340
6 StackedEnsemble_BestOfFamily_2_AutoML_3_20240127_110313 0.7840677 0.4980313
      aucpr mean_per_class_error      rmse       mse
1 0.8973745            0.3770977 0.4026156 0.1620993
2 0.8961402            0.3603275 0.4048651 0.1639157
3 0.8951806            0.3721860 0.4050430 0.1640598
4 0.8952975            0.3393018 0.4051039 0.1641091
5 0.8933682            0.3795073 0.4058725 0.1647325
6 0.8911998            0.3828552 0.4063598 0.1651282

[30 rows x 7 columns] </code></pre>
</div>
<div class="sourceCode cell-code" id="cb52"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb52-1"><a href="#cb52-1" aria-hidden="true" tabindex="-1"></a>auto_model<span class="sc">@</span>leader</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>Model Details:
==============

H2OBinomialModel: stackedensemble
Model ID:  StackedEnsemble_BestOfFamily_4_AutoML_3_20240127_110313 
Model Summary for Stacked Ensemble: 
                                         key            value
1                          Stacking strategy cross_validation
2       Number of base models (used / total)              5/6
3           # GBM base models (used / total)              1/1
4       # XGBoost base models (used / total)              1/1
5           # GLM base models (used / total)              1/1
6           # DRF base models (used / total)              1/2
7  # DeepLearning base models (used / total)              1/1
8                      Metalearner algorithm              GLM
9         Metalearner fold assignment scheme           Random
10                        Metalearner nfolds                5
11                   Metalearner fold_column               NA
12        Custom metalearner hyperparameters             None


H2OBinomialMetrics: stackedensemble
** Reported on training data. **

MSE:  0.09446603
RMSE:  0.3073533
LogLoss:  0.3205342
Mean Per-Class Error:  0.1424296
AUC:  0.9531104
AUCPR:  0.9796067
Gini:  0.9062208

Confusion Matrix (vertical: actual; across: predicted) for F1-optimal threshold:
       Bad Good    Error     Rate
Bad    180   55 0.234043  =55/235
Good    28  523 0.050817  =28/551
Totals 208  578 0.105598  =83/786

Maximum Metrics: Maximum metrics at their respective thresholds
                        metric threshold      value idx
1                       max f1  0.543220   0.926484 254
2                       max f2  0.413375   0.954051 299
3                 max f0point5  0.710304   0.932273 187
4                 max accuracy  0.543220   0.894402 254
5                max precision  0.986866   1.000000   0
6                   max recall  0.282334   1.000000 344
7              max specificity  0.986866   1.000000   0
8             max absolute_mcc  0.543220   0.742174 254
9   max min_per_class_accuracy  0.665172   0.872340 208
10 max mean_per_class_accuracy  0.710304   0.876403 187
11                     max tns  0.986866 235.000000   0
12                     max fns  0.986866 549.000000   0
13                     max fps  0.090883 235.000000 399
14                     max tps  0.282334 551.000000 344
15                     max tnr  0.986866   1.000000   0
16                     max fnr  0.986866   0.996370   0
17                     max fpr  0.090883   1.000000 399
18                     max tpr  0.282334   1.000000 344

Gains/Lift Table: Extract with `h2o.gainsLift(&lt;model&gt;, &lt;data&gt;)` or `h2o.gainsLift(&lt;model&gt;, valid=&lt;T/F&gt;, xval=&lt;T/F&gt;)`

H2OBinomialMetrics: stackedensemble
** Reported on cross-validation data. **
** 5-fold cross-validation on training data (Metrics computed for combined holdout predictions) **

MSE:  0.1620993
RMSE:  0.4026156
LogLoss:  0.4898369
Mean Per-Class Error:  0.3770977
AUC:  0.792586
AUCPR:  0.8973745
Gini:  0.585172

Confusion Matrix (vertical: actual; across: predicted) for F1-optimal threshold:
       Bad Good    Error      Rate
Bad     68  167 0.710638  =167/235
Good    24  527 0.043557   =24/551
Totals  92  694 0.243003  =191/786

Maximum Metrics: Maximum metrics at their respective thresholds
                        metric threshold      value idx
1                       max f1  0.381001   0.846586 331
2                       max f2  0.233628   0.922740 377
3                 max f0point5  0.647875   0.836893 220
4                 max accuracy  0.561549   0.765903 262
5                max precision  0.989967   1.000000   0
6                   max recall  0.107752   1.000000 397
7              max specificity  0.989967   1.000000   0
8             max absolute_mcc  0.647875   0.442688 220
9   max min_per_class_accuracy  0.704439   0.722323 197
10 max mean_per_class_accuracy  0.647875   0.731533 220
11                     max tns  0.989967 235.000000   0
12                     max fns  0.989967 550.000000   0
13                     max fps  0.086524 235.000000 399
14                     max tps  0.107752 551.000000 397
15                     max tnr  0.989967   1.000000   0
16                     max fnr  0.989967   0.998185   0
17                     max fpr  0.086524   1.000000 399
18                     max tpr  0.107752   1.000000 397

Gains/Lift Table: Extract with `h2o.gainsLift(&lt;model&gt;, &lt;data&gt;)` or `h2o.gainsLift(&lt;model&gt;, valid=&lt;T/F&gt;, xval=&lt;T/F&gt;)`
Cross-Validation Metrics Summary: 
               mean       sd cv_1_valid cv_2_valid cv_3_valid cv_4_valid
accuracy   0.771291 0.017618   0.774011   0.778481   0.765517   0.793103
auc        0.794359 0.023192   0.813818   0.774041   0.807381   0.811905
err        0.228709 0.017618   0.225989   0.221519   0.234483   0.206897
err_count 36.000000 4.527693  40.000000  35.000000  34.000000  30.000000
f0point5   0.806521 0.013979   0.800294   0.812030   0.816514   0.818760
          cv_5_valid
accuracy    0.745342
auc         0.764650
err         0.254658
err_count  41.000000
f0point5    0.785007

---
                        mean        sd cv_1_valid cv_2_valid cv_3_valid
precision           0.778744  0.019116   0.773050   0.782609   0.801802
r2                  0.223891  0.038729   0.260007   0.198833   0.238333
recall              0.942947  0.038880   0.931624   0.955752   0.881188
residual_deviance 154.004730 17.749662 176.486950 157.258740 139.797700
rmse                0.402089  0.009688   0.407201   0.403971   0.401237
specificity         0.359130  0.124795   0.466667   0.333333   0.500000
                  cv_4_valid cv_5_valid
precision           0.786260   0.750000
r2                  0.253174   0.169105
recall              0.980952   0.965217
residual_deviance 132.815110 163.665150
rmse                0.386248   0.411789
specificity         0.300000   0.195652</code></pre>
</div>
</div>
</section>
<section id="tài-liệu-tham-khảo" class="level2" data-number="25.5">
<h2 data-number="25.5" class="anchored" data-anchor-id="tài-liệu-tham-khảo"><span class="header-section-number">25.5</span> Tài liệu tham khảo</h2>
<ul>
<li><a href="https://github.com/h2oai/h2o-tutorials">https://github.com/h2oai/h2o-tutorials</a></li>
<li><a href="https://docs.h2o.ai/h2o/latest-stable/h2o-docs/automl.html">https://docs.h2o.ai/h2o/latest-stable/h2o-docs/automl.html</a></li>
</ul>


</section>

</main> <!-- /main -->
<script id="quarto-html-after-body" type="application/javascript">
window.document.addEventListener("DOMContentLoaded", function (event) {
  const toggleBodyColorMode = (bsSheetEl) => {
    const mode = bsSheetEl.getAttribute("data-mode");
    const bodyEl = window.document.querySelector("body");
    if (mode === "dark") {
      bodyEl.classList.add("quarto-dark");
      bodyEl.classList.remove("quarto-light");
    } else {
      bodyEl.classList.add("quarto-light");
      bodyEl.classList.remove("quarto-dark");
    }
  }
  const toggleBodyColorPrimary = () => {
    const bsSheetEl = window.document.querySelector("link#quarto-bootstrap");
    if (bsSheetEl) {
      toggleBodyColorMode(bsSheetEl);
    }
  }
  toggleBodyColorPrimary();  
  const disableStylesheet = (stylesheets) => {
    for (let i=0; i < stylesheets.length; i++) {
      const stylesheet = stylesheets[i];
      stylesheet.rel = 'prefetch';
    }
  }
  const enableStylesheet = (stylesheets) => {
    for (let i=0; i < stylesheets.length; i++) {
      const stylesheet = stylesheets[i];
      stylesheet.rel = 'stylesheet';
    }
  }
  const manageTransitions = (selector, allowTransitions) => {
    const els = window.document.querySelectorAll(selector);
    for (let i=0; i < els.length; i++) {
      const el = els[i];
      if (allowTransitions) {
        el.classList.remove('notransition');
      } else {
        el.classList.add('notransition');
      }
    }
  }
  const toggleColorMode = (alternate) => {
    // Switch the stylesheets
    const alternateStylesheets = window.document.querySelectorAll('link.quarto-color-scheme.quarto-color-alternate');
    manageTransitions('#quarto-margin-sidebar .nav-link', false);
    if (alternate) {
      enableStylesheet(alternateStylesheets);
      for (const sheetNode of alternateStylesheets) {
        if (sheetNode.id === "quarto-bootstrap") {
          toggleBodyColorMode(sheetNode);
        }
      }
    } else {
      disableStylesheet(alternateStylesheets);
      toggleBodyColorPrimary();
    }
    manageTransitions('#quarto-margin-sidebar .nav-link', true);
    // Switch the toggles
    const toggles = window.document.querySelectorAll('.quarto-color-scheme-toggle');
    for (let i=0; i < toggles.length; i++) {
      const toggle = toggles[i];
      if (toggle) {
        if (alternate) {
          toggle.classList.add("alternate");     
        } else {
          toggle.classList.remove("alternate");
        }
      }
    }
    // Hack to workaround the fact that safari doesn't
    // properly recolor the scrollbar when toggling (#1455)
    if (navigator.userAgent.indexOf('Safari') > 0 && navigator.userAgent.indexOf('Chrome') == -1) {
      manageTransitions("body", false);
      window.scrollTo(0, 1);
      setTimeout(() => {
        window.scrollTo(0, 0);
        manageTransitions("body", true);
      }, 40);  
    }
  }
  const isFileUrl = () => { 
    return window.location.protocol === 'file:';
  }
  const hasAlternateSentinel = () => {  
    let styleSentinel = getColorSchemeSentinel();
    if (styleSentinel !== null) {
      return styleSentinel === "alternate";
    } else {
      return false;
    }
  }
  const setStyleSentinel = (alternate) => {
    const value = alternate ? "alternate" : "default";
    if (!isFileUrl()) {
      window.localStorage.setItem("quarto-color-scheme", value);
    } else {
      localAlternateSentinel = value;
    }
  }
  const getColorSchemeSentinel = () => {
    if (!isFileUrl()) {
      const storageValue = window.localStorage.getItem("quarto-color-scheme");
      return storageValue != null ? storageValue : localAlternateSentinel;
    } else {
      return localAlternateSentinel;
    }
  }
  let localAlternateSentinel = 'default';
  // Dark / light mode switch
  window.quartoToggleColorScheme = () => {
    // Read the current dark / light value 
    let toAlternate = !hasAlternateSentinel();
    toggleColorMode(toAlternate);
    setStyleSentinel(toAlternate);
  };
  // Ensure there is a toggle, if there isn't float one in the top right
  if (window.document.querySelector('.quarto-color-scheme-toggle') === null) {
    const a = window.document.createElement('a');
    a.classList.add('top-right');
    a.classList.add('quarto-color-scheme-toggle');
    a.href = "";
    a.onclick = function() { try { window.quartoToggleColorScheme(); } catch {} return false; };
    const i = window.document.createElement("i");
    i.classList.add('bi');
    a.appendChild(i);
    window.document.body.appendChild(a);
  }
  // Switch to dark mode if need be
  if (hasAlternateSentinel()) {
    toggleColorMode(true);
  } else {
    toggleColorMode(false);
  }
  const icon = "";
  const anchorJS = new window.AnchorJS();
  anchorJS.options = {
    placement: 'right',
    icon: icon
  };
  anchorJS.add('.anchored');
  const isCodeAnnotation = (el) => {
    for (const clz of el.classList) {
      if (clz.startsWith('code-annotation-')) {                     
        return true;
      }
    }
    return false;
  }
  const clipboard = new window.ClipboardJS('.code-copy-button', {
    text: function(trigger) {
      const codeEl = trigger.previousElementSibling.cloneNode(true);
      for (const childEl of codeEl.children) {
        if (isCodeAnnotation(childEl)) {
          childEl.remove();
        }
      }
      return codeEl.innerText;
    }
  });
  clipboard.on('success', function(e) {
    // button target
    const button = e.trigger;
    // don't keep focus
    button.blur();
    // flash "checked"
    button.classList.add('code-copy-button-checked');
    var currentTitle = button.getAttribute("title");
    button.setAttribute("title", "Copied!");
    let tooltip;
    if (window.bootstrap) {
      button.setAttribute("data-bs-toggle", "tooltip");
      button.setAttribute("data-bs-placement", "left");
      button.setAttribute("data-bs-title", "Copied!");
      tooltip = new bootstrap.Tooltip(button, 
        { trigger: "manual", 
          customClass: "code-copy-button-tooltip",
          offset: [0, -8]});
      tooltip.show();    
    }
    setTimeout(function() {
      if (tooltip) {
        tooltip.hide();
        button.removeAttribute("data-bs-title");
        button.removeAttribute("data-bs-toggle");
        button.removeAttribute("data-bs-placement");
      }
      button.setAttribute("title", currentTitle);
      button.classList.remove('code-copy-button-checked');
    }, 1000);
    // clear code selection
    e.clearSelection();
  });
  function tippyHover(el, contentFn) {
    const config = {
      allowHTML: true,
      content: contentFn,
      maxWidth: 500,
      delay: 100,
      arrow: false,
      appendTo: function(el) {
          return el.parentElement;
      },
      interactive: true,
      interactiveBorder: 10,
      theme: 'quarto',
      placement: 'bottom-start'
    };
    window.tippy(el, config); 
  }
  const noterefs = window.document.querySelectorAll('a[role="doc-noteref"]');
  for (var i=0; i<noterefs.length; i++) {
    const ref = noterefs[i];
    tippyHover(ref, function() {
      // use id or data attribute instead here
      let href = ref.getAttribute('data-footnote-href') || ref.getAttribute('href');
      try { href = new URL(href).hash; } catch {}
      const id = href.replace(/^#\/?/, "");
      const note = window.document.getElementById(id);
      return note.innerHTML;
    });
  }
      let selectedAnnoteEl;
      const selectorForAnnotation = ( cell, annotation) => {
        let cellAttr = 'data-code-cell="' + cell + '"';
        let lineAttr = 'data-code-annotation="' +  annotation + '"';
        const selector = 'span[' + cellAttr + '][' + lineAttr + ']';
        return selector;
      }
      const selectCodeLines = (annoteEl) => {
        const doc = window.document;
        const targetCell = annoteEl.getAttribute("data-target-cell");
        const targetAnnotation = annoteEl.getAttribute("data-target-annotation");
        const annoteSpan = window.document.querySelector(selectorForAnnotation(targetCell, targetAnnotation));
        const lines = annoteSpan.getAttribute("data-code-lines").split(",");
        const lineIds = lines.map((line) => {
          return targetCell + "-" + line;
        })
        let top = null;
        let height = null;
        let parent = null;
        if (lineIds.length > 0) {
            //compute the position of the single el (top and bottom and make a div)
            const el = window.document.getElementById(lineIds[0]);
            top = el.offsetTop;
            height = el.offsetHeight;
            parent = el.parentElement.parentElement;
          if (lineIds.length > 1) {
            const lastEl = window.document.getElementById(lineIds[lineIds.length - 1]);
            const bottom = lastEl.offsetTop + lastEl.offsetHeight;
            height = bottom - top;
          }
          if (top !== null && height !== null && parent !== null) {
            // cook up a div (if necessary) and position it 
            let div = window.document.getElementById("code-annotation-line-highlight");
            if (div === null) {
              div = window.document.createElement("div");
              div.setAttribute("id", "code-annotation-line-highlight");
              div.style.position = 'absolute';
              parent.appendChild(div);
            }
            div.style.top = top - 2 + "px";
            div.style.height = height + 4 + "px";
            let gutterDiv = window.document.getElementById("code-annotation-line-highlight-gutter");
            if (gutterDiv === null) {
              gutterDiv = window.document.createElement("div");
              gutterDiv.setAttribute("id", "code-annotation-line-highlight-gutter");
              gutterDiv.style.position = 'absolute';
              const codeCell = window.document.getElementById(targetCell);
              const gutter = codeCell.querySelector('.code-annotation-gutter');
              gutter.appendChild(gutterDiv);
            }
            gutterDiv.style.top = top - 2 + "px";
            gutterDiv.style.height = height + 4 + "px";
          }
          selectedAnnoteEl = annoteEl;
        }
      };
      const unselectCodeLines = () => {
        const elementsIds = ["code-annotation-line-highlight", "code-annotation-line-highlight-gutter"];
        elementsIds.forEach((elId) => {
          const div = window.document.getElementById(elId);
          if (div) {
            div.remove();
          }
        });
        selectedAnnoteEl = undefined;
      };
      // Attach click handler to the DT
      const annoteDls = window.document.querySelectorAll('dt[data-target-cell]');
      for (const annoteDlNode of annoteDls) {
        annoteDlNode.addEventListener('click', (event) => {
          const clickedEl = event.target;
          if (clickedEl !== selectedAnnoteEl) {
            unselectCodeLines();
            const activeEl = window.document.querySelector('dt[data-target-cell].code-annotation-active');
            if (activeEl) {
              activeEl.classList.remove('code-annotation-active');
            }
            selectCodeLines(clickedEl);
            clickedEl.classList.add('code-annotation-active');
          } else {
            // Unselect the line
            unselectCodeLines();
            clickedEl.classList.remove('code-annotation-active');
          }
        });
      }
  const findCites = (el) => {
    const parentEl = el.parentElement;
    if (parentEl) {
      const cites = parentEl.dataset.cites;
      if (cites) {
        return {
          el,
          cites: cites.split(' ')
        };
      } else {
        return findCites(el.parentElement)
      }
    } else {
      return undefined;
    }
  };
  var bibliorefs = window.document.querySelectorAll('a[role="doc-biblioref"]');
  for (var i=0; i<bibliorefs.length; i++) {
    const ref = bibliorefs[i];
    const citeInfo = findCites(ref);
    if (citeInfo) {
      tippyHover(citeInfo.el, function() {
        var popup = window.document.createElement('div');
        citeInfo.cites.forEach(function(cite) {
          var citeDiv = window.document.createElement('div');
          citeDiv.classList.add('hanging-indent');
          citeDiv.classList.add('csl-entry');
          var biblioDiv = window.document.getElementById('ref-' + cite);
          if (biblioDiv) {
            citeDiv.innerHTML = biblioDiv.innerHTML;
          }
          popup.appendChild(citeDiv);
        });
        return popup.innerHTML;
      });
    }
  }
});
</script>
<nav class="page-navigation">
  <div class="nav-page nav-page-previous">
      <a href="./p03-05-bagging-boosting.html" class="pagination-link">
        <i class="bi bi-arrow-left-short"></i> <span class="nav-page-text"><span class="chapter-number">24</span>&nbsp; <span class="chapter-title">Bagging, RandomForest và Boosting</span></span>
      </a>          
  </div>
  <div class="nav-page nav-page-next">
      <a href="./p03-08-xgboost.html" class="pagination-link">
        <span class="nav-page-text"><span class="chapter-number">26</span>&nbsp; <span class="chapter-title">XGBoost &amp; LightGBM</span></span> <i class="bi bi-arrow-right-short"></i>
      </a>
  </div>
</nav>
</div> <!-- /content -->



</body></html>