---
title: "Tab guitar"
output: 
  html_document: 
    toc: yes
    highlight: haddock
    theme: flatly
    number_sections: yes
    toc_float: yes
    css: style.css
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

# Nhạc cho Dưa

## Đàn gà con

[F]Trông kia đàn gà [Bb]con lông [F]vàng 

[F]Đi theo mẹ tìm [Bb]ăn trong [F]vườn 

[C]Cùng tìm mồi ăn [F]ngon ngon 

[C]Đàn gà con đi [F]lon ton. 

&nbsp;
 
[F]Thóc vãi rồi nhặt [Bb]ăn cho [F]nhiều 

[F]Uống nước vào là [Bb]no căng [F]diều 

[C]Rồi cùng nhau ta [F]đi chơi 

[C]Đàn gà con xinh [F]kia ơi ! 

## Cả nhà thương nhau

Tone gốc F: Capo 5 

---

&nbsp;
 
Ba thương [C]con vì con giống [Am]mẹ 

Mẹ thương [Dm]con vì [G]con giống [C]ba 

Cả nhà [F]ta cùng thương yêu [C]nhau 

Xa là [G7]nhớ gần nhau là [C]cười. 
 
&nbsp;

Ba thương [C]con vì con giống [Am]mẹ 

Mẹ thương [Dm]con vì [G]con giống [C]ba 

Cả nhà [F]ta cùng thương yêu [C]nhau 

Xa là [G7]nhớ gần nhau là [C]cười. 

Cả nhà [F]ta cùng thương yêu [C]nhau 

Xa là [G7]nhớ gần nhau là [C]cười. 

## Con cò bé bé

Tone gốc F: Capo 5 

---
 
Con [C ]cò bé [Am ]bé nó [F ]đậu cành [Dm ]tre 

Đi không hỏi [F ]mẹ biết [G ]đi đường nào 

Khi [C ]đi em [Am ]hỏi, khi [Dm ]về em [G ]chào 

Miệng [C ]em chúm [Em ]chím mẹ [Dm ]yêu [G ]không [C ]nào. 

## Một gia đình nhỏ một hạnh phúc to

Một nụ cười [C] bé, cha vui cả [Am] ngày

Một vài tiếng [F] khóc, mẹ lo hằng [G] đêm

Thầm cầu mong [Em] cho con sẽ an [Am] lành

Chín tháng sinh [F] thành, một đời yêu [G] thương.

&nbsp;

Một vòng tay [C] lớn ôm con vào [Am] lòng

Một bàn chân [F] to cho con tập [G] đi

Dù ngày mai [Em] kia con lớn nên [Am] người

Nhưng với cha [F] mẹ con mãi bé [G] thơ.

&nbsp;

À ơi à [Am] ơi, con ngủ cho [G] ngoan

Giấc mơ sẽ [C] mang đầy lời mẹ [Am] ru

À ơi à [F] ơi, mãi mãi chúng [G] ta

Một gia đình [E7] nhỏ, một hạnh phúc [Am] to. 

## Twinkle twinkle little star

[Verse 1]

             
[C] Twinkle, twinkle [F] little [C]star.

[F]How I [C] wonder [G7] what you [C] are.

[C]Up [F]above the [C]world so [G7]high,

[C]Like a [F]diamond [C]in the [G7]sky.

[C]Twinkle, twinkle [F]little [C]star.

[F]How I [C]wonder [G7]what you [C]are.

&nbsp;

[Verse 2]

When the blazing sun is gone,

When he nothing shines upon,

Then you show your little light,

Twinkle, twinkle, all the night. 

Twinkle, twinkle little star.

How I wonder what you are.

&nbsp;

[Verse 3]

In the dark blue sky you keep, 

And often through my curtains peep, 

For you never shut your eye, 

Till the sun is in the sky.

Twinkle, twinkle little star.

How I wonder what you are.


## Mary had a little lamb

[A]Mary had a little lamb,

[A]Little lamb, [E]little lamb,

[A]Mary had a little lamb,
                       
Its [E]fleece was white [A]as snow

&nbsp;

Everywhere that Mary went,

Mary went, Mary went,

Everywhere that Mary went

The lamb was sure to go

&nbsp;

It followed her to school one day

School one day, school one day

It followed her to school one day

Which was against the rules.

&nbsp;

It made the children laugh and play,

Laugh and play, laugh and play,

It made the children laugh and play

To see a lamb at school

&nbsp;

And so the teacher turned it out,

Turned it out, turned it out,

And so the teacher turned it out,

But still it lingered near

&nbsp;

And waited patiently about,

Patiently about, patiently about,

And waited patiently about

Till Mary did appear

&nbsp;

"Why does the lamb love Mary so?"

Love Mary so? Love Mary so?

"Why does the lamb love Mary so?"

The eager children cry

&nbsp;

"Why, Mary loves the lamb, you know."

Loves the lamb you know, loves the lamb you know

"Why, Mary loves the lamb, you know."

The teacher did reply

&nbsp;

# Nhạc khác

## Love is blue

[Dm] Ngát [G] xanh, xanh [C] như khung [F] trời


[Dm] Tình yêu màu [Bb] xanh lúc [C] em đã yêu [F] rồi

[Dm] Ấm [G] êm trong [C] đôi tay [F] người

[Dm] Đời bao nồng [Bb] say khi [A7] môi hồng tìm [Dm] môi

&nbsp;

[Dm] Ngát [G] xanh khi [C] em bên [F] chàng

[Dm] Tình yêu màu [Bb] xanh vuốt [C] ve trái tim [F] buồn

[Dm] Đã [G] qua đi [C] cơn mê [F] chiều

[Dm] Mùa xuân vừa [Bb] sang trong [A7] lòng người mình [Dm] yêu

&nbsp;

[D] Tưởng tình [G] ta êm đềm dòng suối [D] mơ

[F#m] Nhưng nắng [Em] lên tình mong [A7] manh như giọt [Dm] sương

&nbsp;

[Dm] Nhớ [G] thương đôi [C] vai rã [F] rời

[Dm] Tình đâu còn [Bb] xanh ngát [C] xanh mắt em [F] cười

[Dm] Tháng [G] năm qua [C] trong âm [F] thầm

[Dm] Đìu hiu đời [Bb] em trong [A7] cơn sầu ngàn [Dm] năm

&nbsp;

[Dm] Xám [G] đen như [C] đêm đông [F] dài

[Dm] Tình sao màu [Bb] đen lúc [C] anh đã đi [F] rồi

[Dm] Khóc [G] lên cho [C] vơi u [F] hoài

[Dm] Trời mưa ngoài [Bb] kia hay [A7] giọt lệ sầu [Dm] rơi

&nbsp;

[Dm] Gió [G] ơi ru [C] chi cơn [F] buồn

[Dm] Tình yêu dở [Bb] dang gẫy [C] đôi cánh thiên [F] thần

[Dm] Xót [G] xa khi [C] đôi tay [F] rời

[Dm] Tình mang màu [Bb] tang chuông [A7] chiều vọng hồn [Dm] em

&nbsp;

[D] Rồi một [G] hôm khi người về lối [D] xưa

[F#m] Nghe ngỡ [Em] ngàng, tình say [A7] xưa vui đại [Dm] dương

&nbsp;

[Dm] Ngát [G] xanh, xanh [C] như trăng [F] thề

[Dm] Tình em lại [Bb] xanh lúc [C] nh đã quay [F] về

[Dm] Cánh [G] tay yêu [C] đương vỗ [F] về

[Dm] Nụ hôn nở [Bb] hoa thay [A7] giọt lệ sầu nhoà [Dm] mi

--------------------------------

[Dm] Sweet, [G] sweet, [C] love is [F] sweet

[Dm] Sweet is my [Bb] life, [C] life in your [F] arms

[Dm] Sweet, [G] sweet, my [C] love is [F] sweet

[Dm] Sweet is my [Bb] life, my [A7] life close to [Dm] you

&nbsp;

[Dm] Blue, [G] blue, [C] love is [F] blue

[Dm] Cradle my [Bb] heart, my [C] loving [F] heart

[Dm] Blue, [G] blue, [C] love is [F] blue

[Dm] Blue like the [Bb] sky which [A7] play in your [Dm] eyes

&nbsp;

[D] Like the [G] water, like the running [D] water

[F#m] Me, my [Em] heart runs [A7] after your [Dm] love

&nbsp;

[Dm] Grey, [G] grey, [C] love is [F] grey

[Dm] My heart [Bb] weeps since [C] you went [F] away

[Dm] Grey, [G] grey, the [C] sky is [F] grey

[Dm] The rain [Bb] falls when you're not [A7] there any [Dm] more

&nbsp;

[Dm] The [G] wind, the [C] wind [F] moans

[Dm] The wind [Bb] weeps since [C] you went [F] away

[Dm] The [G] wind, the [C] cursed [F] wind

[Dm] My heart [Bb] weeps when you're not [A7] there any [Dm] more

&nbsp;

[D] Like the [G] ater, like the running [D] water

[F#m] Me, my [Em] heart runs [A7] after your [Dm] love

&nbsp;

[Dm] Blue, [G] blue, [C] love is [F] blue

[Dm] The sky is [Bb] blue [C] when you [F] return

[Dm] Blue, [G] blue, [C] love is [F] blue

[Dm] Love is [Bb] blue when you [A7] take my [Dm] hand

&nbsp;

[Dm] Mad, [G] mad, [C] love is [F] mad

[Dm] Mad like [Bb] you and [C] mad like [F] me

[Dm] Blue, [G] blue, [C] love is [F] blue

[Dm] Love is [Bb] blue when [A7] I am [Dm] yours


## Tình nông cháy (Over and Over)


Em không mơ [Am] hoang kiếp sống trên cung [E7] hằng

Em không tham lam diễm phúc trên thiên [Am] đàng

Làm sao em [F] nói cho hết những tâm [C] tình

Ước mơ khiêm [E7] nhường có anh bên [Am] mình

&nbsp;

Anh yêu anh [Am] yêu ơi có những đêm đơn [E7] lạnh

Hôn anh hôn trong mơ thấy xót xa riêng [Am] mình

Tình trong đôi [F] mắt xưa ấy nay đâu [C] rồi

Mất anh đêm [E7] này mất anh muôn [Am] đời

&nbsp;

Anh hay chăng [Am] anh nước mắt em vơi [E7] đầy

Anh nghe chăng anh những tiếng em thở [Am] dài

Gọi tên anh [F] mãi trên gối chăn kỷ [C] niệm

Chỉ nghe trong [E7] lòng tiếc thương âm [Am] thầm

&nbsp;

Như bao cây [Am] xanh trước gió đông cây [E7] vàng

Xa anh hôm nay thấy giấc mơ hoang [Am] tàn

Vòng tay âu [F] yếm em ngỡ như thiên [C] đàng

Đến nay chỉ [E7] là đắng cay bẻ [Am] bàng 

&nbsp;

----------------------------

[Am] I never dare to reach for the [E7] moon

I never tought I'd know heaven so [Am] soon

I couldn't [F] hope to say how I [C] feel

The joy in my [E7] heart no words can [Am] reveal

&nbsp;

[Am] Over and over I whisper your [E7] name

Over and over I kiss you [Am] again

I see the [F] light of love in your [C] eyes

Love is for [E7] ever,no more good [Am] bye

&nbsp;

[Am] Now just a memory the tears that I [E7] cried

Now just a memory the sighs that I [Am] sighed

Dreams that I [F] cherished all have come [C] true

All my[E7] tomorrows I give to [Am] you

&nbsp;

[Am] Life's summer leaves may turn into [E7] gold

The love that we share will never grow [Am] old

Here in your [F] arms no words far [C] away

Here in your [E7] arms forever I'll [Am] stay

## Donna Donna

[Am] Mái nhà [E] xưa yêu dấu,

[Am] Bức tường [E] rêu phong cũ [Am] nơi cậu bé [Dm] qua những [Am] ngày thơ [E] ấu.

[Am] Muốn mình [E] mau khôn lớn, [Am] giữa lụa [E] là yên ấm [Am]

Em ngồi [Dm] ước mơ bước [Am] chân [E] giang [Am] hồ.

&nbsp;

[G] Mơ bay theo cánh [C] chim ngang [Am] trời,

[Dm] biển xa núi chơi [C] vơi.

[G] Mơ bay đi khát [C] khao cuộc [Am] đời. 

Một đêm [E] nhớ tiếng ai ru [Am] hời.

&nbsp;

[E] Donna Donna Donna [Am] ngủ đi nhé.

[Dm] Ngoài trời đường nhiều [G] gió tuyết [C] rơi.

[E] Donna Donna Donna [Am] ngủ đi nhé.

[E] Hãy nằm trong cánh tay của [Am] mẹ.

&nbsp;

Có một [E] người đàn ông, [Am] trước thềm [E] nhà rêu phong

[Am] bỗng ngồi [Dm] khóc nhớ những [Am] ngày thơ [E] ấu.

[Am] Sống đời [E] bao cay đắng, [Am] tóc bạc [E] phai mưa [Am] nắng.

Tay đành [Dm] trắng những giấc [Am] mơ [E] thơ [Am] dại.

&nbsp;

[G] Đi qua bao núi [C] sông gập [Am] ghềnh.

[Dm] Cuộc tình mãi lênh [C] đênh.

[G] Đi qua bao tháng [C] năm vô [Am] tình

Một đêm [E] nhớ tiếng ru mẹ [Am] hiền

&nbsp;

Donna Donna Donna [Am] ngủ đi nhé.

[Dm] Ngoài trời đường nhiều [G] gió tuyết [C] rơi.

[E] Donna Donna Donna [Am] ngủ đi nhé,

[E] Hãy nằm trong cánh tay của [Am] mẹ

&nbsp;


---

[Am] On a [E] wagon [Am] bound for [E] market

[Am] There's a [Am] calf with a [Am] mournful [E] eye

[Am] High above [E] him [Am] there's [E] a [Am] swallow

Winging [Dm] swiftly [Am] through [E] the [Am] sky

&nbsp;

[G] How the [C] winds are [Am] laughing

[Dm] They laugh with all their [C] might

[G] Laugh and laugh the [C] whole day [Am] through

And [E] half the summer's [Am] night

&nbsp;

[E] Donna, Donna, Donna, [Am] Donna

[Dm] Donna, Donna, [G] Donna, [C] Don

[E] Donna, Donna, Donna, [Am] Donna

[E] Donna, Donna, Donna, [Am] Don

&nbsp;

"Stop [E] complaining", [Am] said the [E] farmer

[Am] Who told [Dm] you a [Am] calf to [E] be?

[Am] Why don't [E] you [Am] have [E] wings to fly [Am] with

Like the [Dm] swallow so [Am] proud [E] and [Am] free?

&nbsp;

[G] How the [C] winds are [Am] laughing

[Dm] They laugh with all their [C] might

[G] Laugh and laugh the [C] whole day [Am] through

And [E] half the summer's [Am] night

&nbsp;

[E] Donna, Donna, Donna, [Am] Donna

[Dm] Donna, Donna, [G] Donna, [C] Don

[E] Donna, Donna, Donna, [Am] Donna

[E] Donna, Donna, Donna, [Am] Don

&nbsp;

[Am] Calves are [E] easily [Am] bound and [E] slaughtered

[Am] Never [Dm] knowing [Am] the reason [E] why

[Am] But who [E] ever [Am] treasures [E] free [Am] dom

Like the [Dm] swallow [Am] has [E] learned to [Am] fly

&nbsp;

[G] How the [C] winds are [Am] laughing

[Dm] They laugh with all their [C] might

[G] Laugh and laugh the [C] whole day [Am] through

And [E] half the summer's [Am] night

&nbsp;

[E] Donna, Donna, Donna, [Am] Donna

[Dm] Donna, Donna, [G] Donna, [C] Don

[E] Donna, Donna, Donna, [Am] Donna

[E] Donna, Donna, Donna, [Am] Don

## Người tình mùa đông

Đường vào [C]tim em ôi băng [Em]giá 

Trời mùa [Am]đông mây vẫn hay đi [Em]về 

Vẫn [Dm]mưa mưa rơi trên đường thầm [Am]thì 

Vì [F]đâu mưa em không [G]đến 

&nbsp;

Đường vào [C]tim em mây giăng [Em]kín 

Bàn chân [Am]anh trên lối đi không [Em]thành 

Những [Dm]đêm khuya mưa buồn một [Am]mình 

Có [G]khi cho ta quên cuộc [Am]tình 

&nbsp;
 
Từng cơn [C]mưa hắt hiu bên ngoài song [Em]thưa 

Lắm khi mưa làm hồn [E7]ta nhớ mãi ngày [Am]qua 

Nhớ con [F]phố xưa vẫn âm thầm đợi [C]chờ 

Nhớ đôi vai [Dm]ngoan em sợ trời mưa [Em]gió 

&nbsp;
 
Từng ngày [C]ta vẫn đưa em về qua [Em]phố 

Vẫn chim cao trời mưa [E7]lũ vẫn tiếng buồn [Am]xưa 

Ôi bàn [F]tay ai đã dắt em chiều [G]nay 

&nbsp;


## Nhỏ ơi

Lần đầu(Dm) ta gặp nhỏ( C), trong nắng(Am) chiều bay bay(Dm)

Ngập ngừng(Dm) ta hỏi nhỏ( C), nhỏ bảo( C) nhỏ không tên(F)

Ừ thì(Dm) nhỏ không tên( C), bây giờ( C) quen nhé nhỏ(Am), nhỏ ơi(Dm)

&nbsp;

NHỎ ƠI!

&nbsp;

Lần đầu(Dm) ta gặp nhỏ( C), trong nắng(Am) chiều bay bay(Dm)

Ngập ngừng(Dm) ta hỏi nhỏ( C), nhỏ bảo( C) nhỏ không tên(F)

Ừ thì(Dm) nhỏ không tên( C), bây giờ( C) quen nhé nhỏ(Am), nhỏ ơi(Dm)

&nbsp;

Lần này ta gặp nhỏ, trong nắng chiều bay bay

Ngập ngừng ta hỏi nhỏ, nhỏ bảo nhỏ chưa yêu

Ừ thì nhỏ chưa yêu, bây giờ yêu nhé nhỏ, nhỏ ơi

&nbsp;

Lần này(Dm), nhỏ quay đi( C), không thèm( C) nhìn ta nữa(Am)

Giọt sầu(Dm) rơi một mình( C), chỉ còn(Dm) ta một mình( C), nhỏ ơi (Dm)

&nbsp;

Còn gì đâu hỡi người, trong nắng chiều phôi phai

Kỷ niệm ta cùng nhỏ, giờ chỉ là hư vô

Nụ cười là hư vô, xa rồi vẫn nhớ hoài, nhỏ ơi.

&nbsp;

Tình cờ ta gặp nhỏ, trong nắng vàng ban mai

Thẹn thùng ta hỏi nhỏ, nhỏ bảo khờ ghê đi

Ừ thì khờ ghê đi, thương rồi sao chẳng hiểu, nhỏ ơi

&nbsp;

## Huyền thoại rượu

(Em)Ai trên đời chẳng uống (Am)rượu 

mà đã uống rượu là (Em)phải say. 

Rượu mà uống không say(Dm) 

không phải hay uống (Em)rượu,

không phải hay uống rượu (Am)

mà rượu  là rượu mà(Am) bia là bia

&nbsp;

Ai trên đời chẳng sợ vợ, mà chẳng sợ vợ thì sợ ai
Thủa con bé t hi sợ ma, khi làm cha thì sợ vợ
Vô sinh viên thì sợ nợ, mà nợ thì nợ mà chơi thì chơi

&nbsp;

Đêm mắc màn ngủ với vợ, nghe đến rượu rồi lại đi
Vợ mà nói năng chi đây là cho 1 đạp
Đấy là cho 1 đạp mà vợ là vợ mà ta là ta

&nbsp;

Vợ cầm chén liên tay ta cầm chai ta đập lại
Trong cuộc chiến điêu tàn mà vợ là vợ mà ta là ta
Vợ thì vi như cơm em thì ví như hàng phở
Cơm mà khê thì đi ăn phở, mà phở là phở mà cơm là cơm

&nbsp;

Ai trên đời chẳng uống rượu mà đã uống rượu là phải say
Rượu thì năm ba chai bia thì vài ba vại
Ai uống bia thì đừng uống rượu mà đã uống rượu thì đừng uống bia

&nbsp;

Ai trên đời chẳng sợ vợ, mà chẳng sợ vợ thì sợ ai
Vợ là đấng tối cao hay là con sư tử nhưng mà ta kết bạn cho đời bớt cô đơn
Vì hạnh phúc quốc gia, ta phải đi cho bằng được
Ai nói xuôi nói ngược mà vợ là vợ mà ta là ta

&nbsp;

Ai trên đời mà chẳng sợ, chẳng sợ mẹ thì sợ ba, hồi còn bé ngán Ma, sang Balan thì sợ nợ, nhưng mà ta không sợ, nợ nhiều thì (ta) bùng luôn.

---

&nbsp;

Khi vô trường là phải học, mà đã học là phải thi, Bộ quy chế mới ra, “thi lần ba mà chẳng được”, thi lần tư cũng chẳng sợ, đuổi học thì về quê.

&nbsp;

Khi ra trường là bỏ rượu, mà bỏ rượu là tợp bia, mình chỉ uống bia hơi, ai thảnh thơi mà tợp rượu, ta kĩ sư tiền triệu, phải bỏ rượu, tợp bia.

&nbsp;

Bia bao giờ chẳng có bọt, chẳng có bọt chẳng phải bia, và từ rất xưa kia, bia mà ngon là nhờ bọt, không phải chua, không phải ngọt, càng nhiều bọt càng ngon.

&nbsp;

Hôm nay ngồi mà nhớ lại, cuộc tình đầu ngày xưa, tình thì rất đắm say, em lại đi lấy chồng, để mình anh chờ đợi, em làm tội đời anh.

&nbsp;

Đêm chong đèn ngồi nhớ rượu, buộc hai cẳng phải đi, dù vợ có mắng ta, ta phải đi bằng được, ai làm chi cũng mặc, vợ không thể cản ta.

&nbsp;

Vui hay buồn mình cũng nhậu, mà đã nhậu là phải say. Rượu mà uống đếch say, đếch thấy hay của rượu, ai làm chi ta cũng mặc, vì đã nhậu là phải say.

&nbsp;

Đi mua rượu về mới nhậu, vợ cũng nhậu cùng ta, vợ cầm bát ném ta, ta cầm chai đập lại, sau trận chiến tơi bời, vợ gục dưới chân ta.

&nbsp;

Vợ trên đầu, vợ trên cổ, vợ làm khổ đời ta, vợ ngoan ngoãn ta thương, vợ đành hanh ta nện, có gì đâu mà sợ, vợ là vợ của ta.

&nbsp;

Ai trên đời chẳng lấy vợ, vợ là nợ đời ta. Thà rằng cứ như ta, ta thà ly dị vợ, để từng đêm đi nhậu, chẳng sợ vợ rầy la.

&nbsp;

Đêm chong đèn ngồi đếm bạc, tờ năm chục màu xanh, mẹ cầm súng đứng canh, con cầm dao ngồi cạnh, đừa nào vô thì khó chạy, mẹ là mẹ của ta.

## Chị tôi

[Am] Nhà tôi trên bến [G] sông có chiếc cầu [Am] nhỏ cong cong 

Hàng [C] cau dưới nắng [G] trong lá [Am] trầu không 

[C] Chị tôi trông dễ [Gm] thương bán rau [Dm] chợ cầu Đông í a 

[Am] Chị tôi chưa lấy chồng. 

&nbsp;

[Am] Thời con gái lưng [G] ong có bao người [Am] thầm mong theo 

Mẹ [C] giục con gái [G] yêu lấy [Am] chồng đi 

[C] Chị thương hai đứa [Gm] em thương mẹ [Dm] già con đau í a 

[Am] Chị tôi chưa lấy chồng. 

&nbsp;

[Am] Rồi mẹ tôi khuất [G] xa, chúng tôi không [Am] còn thơ ngây 

Chị [C] lại lo các [G] em chuyện [Am] chồng con 

[C] Ngày chia tay bến [Gm] sông thấy chị [Dm] buồn mà thương í a 

[Am] Chị tôi chưa lấy chồng. 

&nbsp;

[Am] Rồi một đêm sáng [G] trong có một người [Am] đàn ông qua 

Họ [C] về xây chiếc [G] cầu nối [Am] bờ sông 

[C] Gặp chị tôi dễ [Gm] thương mới xin [Dm] lời cầu hôn í a 

[Am] Chị cũng muốn lấy chồng. 

&nbsp;

[Am] Cầu xây xong đã [G] lâu không thấy người [Am] về đưa dâu 

Để [C] chị tôi ngóng [G] chờ mắt lệ [Am] nhòa 

[C] Hàng cau đâu trái [Gm] cau bao lá [Dm] trầu buồn rơi theo 

[Am] Chị tôi chưa lấy chồng. 

&nbsp;

[Am] Nhiều năm xa cách [G] xa tôi trở về làng [Am] quê thăm 

Nhìn [C] hàng cau xác [G] xơ lá trầu [Am] khô 

[C] Mộ chị tôi bé [Gm] xinh đứng bên cầu [Dm] lẻ loi í a

[Am] Mộ người chưa có chồng.

&nbsp;

[F] Chị tôi chưa [G] lấy [Am] chồng.. 


## Tình lỡ cách xa

[Am] Một mùa thu [C] qua có [Dm] em bên giấc [E] mộng,

[Am] Tình hồng chưa [C] phai cớ [D] sao em lại [E7] xa

[Am] Từ ng chiếc lá nhẹ [C] rơi đường [D] phố vắng buồn [Am] tênh

Người ra [F] đi khúc biệt [E] ly rất [Am] buồn.

&nbsp;

[Am] Lời nào cho [C] anh phút [Dm] giây ta ấm [E] nồng

[Am] Tình hồng như [C] mơ có [D] em yêu mình [E7] anh,

[Am] Giờ phút cuối nhẹ [C] trôi đường [D] phố vắng mình [Am] em

Người quay [F] lư ng giấc mộng [E] xưa úa [Am] tàn.

&nbsp;

Trời mưa [F] tuôn ngoài đêm [G] vắng nhớ [C] em

Bàn tay [F] anh bao khát [G] khao đợi [E] chờ.

Người [Am] đã đến với [Em] anh thì [F] mãi mãi có [C] nhau

Dù [F] cho bao tháng [G] năm có [C] trôi đi vào quên [E] lãng.

Tình [Am] lỡ nếu cách [Em] xa thì [Dm] mãi mãi nhớ [Am] nhau

Bao câu [F] hát chỉ [G] yêu một [Dm] người [Em] mình [G] em [Am] thôi.
